docs/docs/actions/validators.md
examples/ent-rsvp/backend/src/ent/address/actions/address_builder.ts
examples/ent-rsvp/backend/src/ent/auth_code/actions/auth_code_builder.ts
examples/ent-rsvp/backend/src/ent/event/actions/event_builder.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/event_activity_builder.ts
examples/ent-rsvp/backend/src/ent/guest/actions/guest_builder.ts
examples/ent-rsvp/backend/src/ent/guest_data/actions/guest_data_builder.ts
examples/ent-rsvp/backend/src/ent/guest_group/actions/guest_group_builder.ts
examples/ent-rsvp/backend/src/ent/user/actions/user_builder.ts
examples/simple/src/ent/address/actions/address_builder.ts
examples/simple/src/ent/auth_code/actions/auth_code_builder.ts
examples/simple/src/ent/contact/actions/contact_builder.ts
examples/simple/src/ent/event/actions/event_builder.ts
examples/simple/src/ent/event/actions/event_validators.ts
examples/simple/src/ent/holiday/actions/holiday_builder.ts
examples/simple/src/ent/hours_of_operation/actions/hours_of_operation_builder.ts
examples/simple/src/ent/user/actions/user_builder.ts
internal/field/field.go
internal/tscode/builder.tmpl

simplifies the API in triggers/validators or observers
fixes https://github.com/lolopinto/ent/issues/334
updates examples

add data getters to Builder 

---

.github/workflows/node.js.yml
docs/docs/intro.md

ran through the intro again and found a few small things to fix

update some docs

---

docs/docs/intro.md
ts/package.json
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/core/privacy.ts

to be clearer about what's happening when they fail
fixes https://github.com/lolopinto/ent/issues/254 and https://github.com/lolopinto/ent/issues/336

change error messages for actions 

---

ts/package-lock.json
ts/packages/ent-email/package-lock.json
ts/packages/ent-graphql-tests/package-lock.json
ts/packages/ent-passport/package-lock.json
ts/packages/ent-password/package-lock.json
ts/packages/ent-phonenumber/package-lock.json

run `npm upgrade` all over the place

Dependabot updates

---

examples/ent-rsvp/backend/src/ent/address/actions/generated/delete_address_action_base.ts
examples/ent-rsvp/backend/src/ent/address/actions/generated/edit_address_action_base.ts
examples/ent-rsvp/backend/src/ent/event/actions/generated/delete_event_action_base.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/delete_event_activity_action_base.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/edit_event_activity_action_base.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/edit_event_activity_rsvp_status_action_base.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/event_activity_add_invite_action_base.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/event_activity_remove_invite_action_base.ts
examples/ent-rsvp/backend/src/ent/guest/actions/generated/delete_guest_action_base.ts
examples/ent-rsvp/backend/src/ent/guest/actions/generated/edit_guest_action_base.ts
examples/ent-rsvp/backend/src/ent/guest_data/actions/generated/delete_guest_data_action_base.ts
examples/ent-rsvp/backend/src/ent/guest_data/actions/generated/edit_guest_data_action_base.ts
examples/ent-rsvp/backend/src/ent/guest_group/actions/generated/delete_guest_group_action_base.ts
examples/ent-rsvp/backend/src/ent/guest_group/actions/generated/edit_guest_group_action_base.ts
examples/ent-rsvp/backend/src/ent/tests/event_activity.test.ts
examples/simple/src/ent/auth_code/actions/generated/delete_auth_code_action_base.ts
examples/simple/src/ent/contact/actions/generated/delete_contact_action_base.ts
examples/simple/src/ent/contact/actions/generated/edit_contact_action_base.ts
examples/simple/src/ent/event/actions/generated/delete_event_action_base.ts
examples/simple/src/ent/event/actions/generated/edit_event_action_base.ts
examples/simple/src/ent/event/actions/generated/edit_event_rsvp_status_action_base.ts
examples/simple/src/ent/event/actions/generated/event_add_host_action_base.ts
examples/simple/src/ent/event/actions/generated/event_remove_host_action_base.ts
examples/simple/src/ent/user/actions/generated/confirm_edit_email_address_action_base.ts
examples/simple/src/ent/user/actions/generated/confirm_edit_phone_number_action_base.ts
examples/simple/src/ent/user/actions/generated/delete_user_action_base.ts
examples/simple/src/ent/user/actions/generated/edit_email_address_action_base.ts
examples/simple/src/ent/user/actions/generated/edit_phone_number_action_base.ts
examples/simple/src/ent/user/actions/generated/edit_user_action_base.ts
internal/tscode/action_base.tmpl

fixes https://github.com/lolopinto/ent/issues/333
this is a simple and ugly-ish fix. long term we may want to build something into Orchestrator that takes a method to run before validating or saving

cleanup edge group action

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/edit_event_activity_rsvp_status_action_base.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/event_activity_remove_invite_action_base.ts
examples/ent-rsvp/backend/src/ent/generated/address_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_group_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_query_base.ts
examples/ent-rsvp/backend/src/ent/tests/address.test.ts
examples/ent-rsvp/backend/src/ent/tests/event.test.ts
examples/ent-rsvp/backend/src/ent/tests/event_activity.test.ts
examples/ent-rsvp/backend/src/ent/tests/guest_group.test.ts
examples/ent-rsvp/backend/src/graphql/mutations/generated/email_available_type.ts
examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/generated/event_query_base.ts
examples/simple/src/ent/generated/user_query_base.ts
examples/simple/src/ent/hours_of_operation/actions/generated/create_hours_of_operation_action_base.ts
examples/simple/src/ent/tests/user.test.ts

new versions. update tests based on changes. prettier changes because of https://prettier.io/blog/2021/05/09/2.3.0.html#improve-visual-separation-between-header-and-body-in-classes-with-multiline-headers-10085httpsgithubcomprettierprettierpull10085-by-sosukesuzukihttpsgithubcomsosukesuzuki etc

 Update examples

---

docs/docs/ent-schema/actions.md

It should be `eventDelete` instead of `deleteEvent`

fix typo in event mutation generated

---

examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
examples/todo-sqlite/src/ent/generated/account_base.ts
examples/todo-sqlite/src/ent/generated/tag_base.ts
examples/todo-sqlite/src/ent/generated/todo_base.ts
examples/todo-sqlite/src/ent/tests/todo.test.ts
examples/todo-sqlite/src/ent/testutils/util.ts
examples/todo-sqlite/src/graphql/tests/todo.test.ts
internal/enttype/type.go
internal/enttype/types_test.go
internal/graphql/generate_ts_code.go
internal/schema/node_data.go
internal/tscode/base.tmpl
internal/tscode/step.go
ts/package.json
ts/src/core/convert.ts
ts/src/index.ts
ts/src/testutils/builder.ts
ts/src/testutils/fake_data/fake_contact.ts
ts/src/testutils/fake_data/fake_event.ts
ts/src/testutils/fake_data/fake_user.ts

for now this only works for sqlite: booleans and dates
eventually, will need this for lists,json objects and other complex types

support converting value out of db into expected representation

---

ent/data/data.go
ent/loader.go
ent/loader_test.go
test_setup/main.go

broken by https://github.com/lolopinto/ent/pull/370/files#diff-c5b372ec274f3d44d99e8316cbd7ce357506cf96f9fb433cf132bdcdf2711870
ran into an issue working with a new product when new version was being created at https://github.com/lolopinto/ent/pull/374

golang: fix issue with checking for edges when table doesn't exist

---

docs/docs/intro.md

I tried to run the project with Node 12 and it went pop

Documentation Updates

---

ts/package.json
ts/src/scripts/custom_graphql.ts

need to also update this.
followup to https://github.com/lolopinto/ent/pull/377

snowtop update

---

examples/simple/src/graphql/index.ts

re https://github.com/lolopinto/ent/issues/378

update example to support both JWT and session based flows 

---

release_image/main.go
ts/Dockerfile
ts/Dockerfile.tmpl

pointing at https://github.com/lolopinto/ent/releases/tag/v0.0.19

new dockerfile version 

---

examples/ent-rsvp/backend/Dockerfile
examples/ent-rsvp/backend/develop.Dockerfile
examples/ent-rsvp/backend/docker-compose.dev.yml
examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/Dockerfile
examples/simple/develop.Dockerfile
examples/simple/docker-compose.dev.yml
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/Dockerfile
examples/todo-sqlite/develop.Dockerfile
examples/todo-sqlite/docker-compose.dev.yml
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package-lock.json
ts/package.json
ts/src/core/db.ts
ts/src/core/ent.ts
ts/src/core/logger.ts
ts/src/testutils/db/test_db.ts
ts/src/testutils/db_mock.test.ts

make better-sqlite3 optional. helps with [smaller image](https://github.com/lolopinto/ent/pull/401) and simplifies every non-sqlite path.
Sqlite path is slightly more complicated but that's fine.

Better sqlite optional

---

ent/sql_test.go
internal/db/db_schema_test.go
internal/depgraph/depgraph_test.go
internal/edge/edge_test.go
internal/graphql/graphql_schema_test.go
internal/parsehelper/parse_file.go

convert everything to use assert and require
the inconsistency in the code not ideal

migrate away from t.errorf

---

internal/action/action_test.go
internal/db/db_schema_test.go
internal/edge/edge.go
internal/field/field.go
internal/field/fields_test.go
internal/schema/node_data_info.go
internal/schema/schema.go
internal/schema/schema_constraints_test.go
internal/schema/schema_input_test.go

fixes https://github.com/lolopinto/ent/issues/329
builds on top of https://github.com/lolopinto/ent/pull/405

validate multi-column foreign keys

---

python/auto_schema/auto_schema/change_type.py
python/auto_schema/auto_schema/clause_text.py
python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/auto_schema/diff.py
python/auto_schema/auto_schema/ops.py
python/auto_schema/auto_schema/ops_impl.py
python/auto_schema/auto_schema/renderers.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/setup.py
python/auto_schema/tests/conftest.py
python/auto_schema/tests/runner_test.py

needed in golang CLI to detect what db changes have happened
run as follows:
```
LOCAL_AUTO_SCHEMA=true python3 auto_schema/cli/__init__.py -e postgresql://ola:@localhost/tsent_test -s /Users/ola/code/ent/examples/simple/src/schema  --changes
{"users": [{"change": "add_column", "desc": "add column bar to table users", "col": "bar"}]}
```
and when there's no change:
```
LOCAL_AUTO_SCHEMA=true python3 auto_schema/cli/__init__.py -e postgresql://ola:@localhost/tsent_test -s /Users/ola/code/ent/examples/simple/src/schema  --changes
{}
```

auto_schema: CLI command to get changes

---

python/auto_schema/auto_schema/change_type.py
python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/setup.py

was checking the wrong value for changes

fix issue from https://github.com/lolopinto/ent/pull/408

---

ts/packages/ent-email/package-lock.json
ts/packages/ent-email/package.json
ts/packages/ent-password/package-lock.json
ts/packages/ent-password/package.json

also publish new versions of packages

bump tar for security reasons

---

.github/workflows/update-docs.yml

uses github actions and https://github.com/marketplace/actions/merge-branch action specifically

updadte docs branch when docs are update so that it's auto-pushed

---

docs/docs/custom-code/custom-accessors.md
docs/docs/custom-code/custom-mutations.md
docs/docs/custom-code/custom-queries.md
docs/docs/custom-code/file-uploads.md
docs/docs/custom-code/gql-context.md
docs/docs/custom-code/gql-field.md
docs/docs/intro.mdx

broken in https://github.com/lolopinto/ent/pull/416
(also retrying auto update docs via branch merging) since docs-live has been force pushed to current main

fix broken links in docs

---

.github/workflows/docs_build.yml
README.md
docs/docusaurus.config.js

e.g. no missing links when docs are changed like https://github.com/lolopinto/ent/pull/418

CI for docs site so that we confirm the build works 

---

ts/package.json
ts/src/testutils/db/test_db.ts

support unique: https://github.com/lolopinto/ent/issues/298
support enum type: https://github.com/lolopinto/ent/issues/297

minor TempDB updates

---

docs/docs/advanced-topics/clause.md
ts/src/core/clause.test.ts
ts/src/core/clause.ts
ts/src/index.ts

This PR attempts to add a 'not equals' clause - although I've no idea how to run the tests so it's yolo'd by eye only. Be warned!
Hopefully it's a pretty trivial change tho?

Adds a 'not equals' clause

---

docs/docs/intro.mdx
internal/codegen/prompts.go

don't require local postgres anymore
can use [postgres docker image](https://github.com/lolopinto/ent-starter#postgres-docker-image)
also, change prompt a little

update docs to reference postgres image

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/ent/event/actions/create_event_action.ts
examples/ent-rsvp/backend/src/ent/event/actions/generated/create_event_action_base.ts
examples/ent-rsvp/backend/src/ent/tests/event.test.ts
examples/ent-rsvp/backend/src/graphql/mutations/generated/event/event_create_type.ts
examples/ent-rsvp/backend/src/graphql/schema.gql
examples/ent-rsvp/backend/src/graphql/tests/event_activity_type.test.ts
examples/ent-rsvp/backend/src/graphql/tests/event_query_type.test.ts
examples/ent-rsvp/backend/src/schema/event.ts
examples/ent-rsvp/ent-rsvp-web/README.md
examples/ent-rsvp/ent-rsvp-web/next-env.d.ts
examples/ent-rsvp/ent-rsvp-web/pages/home.tsx
examples/ent-rsvp/ent-rsvp-web/schema.graphql
examples/ent-rsvp/ent-rsvp-web/src/__generated__/eventCreateMutation.graphql.ts

it shows things working and shows cleaner GraphQL and client code.
added in https://github.com/lolopinto/ent/pull/437

update ent-rsvp example to use defaultToViewerOnCreate

---

examples/ent-rsvp/backend/package-lock.json
examples/simple/package-lock.json
examples/todo-sqlite/package-lock.json
internal/tscode/step.go

this is a quick fix. will refactor and fix correctly later

fix error generating queries when no actions exist

---

examples/ent-rsvp/backend/src/testutils/index.ts

broken by https://github.com/lolopinto/ent/pull/441
would have been caught if https://github.com/lolopinto/ent/issues/304 was fixed

fix ent-rsvp-backend tests

---

ts/package-lock.json
ts/package.json

https://www.npmjs.com/package/graphql-upload depends on this but hasn't been updated yet

update object-path dependency because dependabot

---

docs/docs/advanced-topics/running-locally.md
ts/Dockerfile
ts/Dockerfile.tmpl
ts/package-lock.json
ts/package.json

updated to latest versions of https://www.npmjs.com/package/typescript
https://www.npmjs.com/package/prettier
https://www.npmjs.com/package/tsconfig-paths
https://www.npmjs.com/package/ts-node

scope nodejs installs instead of always installing the latest

---

release_image/main.go

* change cache image to one per node version. still not sure this is the best way
* remove channel usage and always use waitgroup. the `defer os.RemoveAll()` line wasn't always being called
* move removing of builder to use defer. 
now there's 3 defers and since it's LIFO, order is 
* remove builder
* remove file
* call wg.Done()

refactor build docker image code

---

.github/workflows/node.js.yml
ts/src/core/config.ts

there's apparently a [bug in nodejs 16.9](https://github.com/nodejs/node/issues/40030) which is what is leading to [these](https://github.com/lolopinto/ent/pull/478) [issues](https://github.com/lolopinto/ent/pull/477)

use node 16.8

---

.github/workflows/node.js.yml
ts/src/core/config.ts

This reverts commit 0770656a0f18a1c702bd1149c2041dc6df72c497.
reverting https://github.com/lolopinto/ent/pull/480

Revert "use node 16.8 (#480)"

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/packages/ent-email/package-lock.json
ts/packages/ent-email/package.json
ts/packages/ent-graphql-tests/package-lock.json
ts/packages/ent-graphql-tests/package.json
ts/packages/ent-passport/package-lock.json
ts/packages/ent-passport/package.json
ts/packages/ent-password/package-lock.json
ts/packages/ent-password/package.json
ts/packages/ent-phonenumber/package-lock.json

update everything (packages and examples) to latest version of jest ala https://github.com/lolopinto/ent/pull/478
+ npm audit to fix things
+ delete package-lock.json and node_modules to install latest versions of all deps

Dependabot

---

examples/ent-rsvp/backend/src/ent/generated/address_base.ts
examples/ent-rsvp/backend/src/ent/generated/auth_code_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_data_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_group_base.ts
examples/ent-rsvp/backend/src/ent/generated/user_base.ts
examples/simple/src/ent/generated/address_base.ts
examples/simple/src/ent/generated/auth_code_base.ts
examples/simple/src/ent/generated/comment_base.ts
examples/simple/src/ent/generated/contact_base.ts
examples/simple/src/ent/generated/event_base.ts
examples/simple/src/ent/generated/holiday_base.ts
examples/simple/src/ent/generated/hours_of_operation_base.ts
examples/simple/src/ent/generated/user_base.ts
examples/todo-sqlite/src/ent/generated/account_base.ts
examples/todo-sqlite/src/ent/generated/tag_base.ts
examples/todo-sqlite/src/ent/generated/todo_base.ts
internal/tscode/base.tmpl

and can expose it if they want.
need this to build a simple version of something like edit history

make data protected in base classes so that subclasses have access to it

---

ts/package.json

for https://github.com/lolopinto/ent/pull/531 and https://github.com/lolopinto/ent/pull/533

new @snowtop/ent version

---

gent/cmd/downgrade.go
internal/db/db_schema.go
python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/auto_schema/command.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/tests/command_test.py
python/auto_schema/tests/runner_test.py
python/auto_schema/tests/testingutils.py
tsent/cmd/downgrade.go
tsent/cmd/root.go

has always annoyed me and now time to fix it
fixes https://github.com/lolopinto/ent/issues/118

auto_schema: delete alembic version file when downgrade is run

---

python/auto_schema/auto_schema/command.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/tests/command_test.py
python/auto_schema/tests/testingutils.py

addresses https://github.com/lolopinto/ent/issues/530

auto_schema: squash given a parameter squashes last N changes into one

---

examples/simple/src/ent/user/actions/generated/user_builder.ts
examples/simple/src/graphql/resolvers/generated/user_type.ts
examples/simple/src/schema/schema.py

fix issues from merging
https://github.com/lolopinto/ent/commit/d2382db8b43ca479d9fba818980888cac367033e

reapply codegen in example

---

python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/auto_schema/command.py
python/auto_schema/setup.py
tsent/cmd/alembic.go

https://github.com/lolopinto/ent/pull/544
https://github.com/lolopinto/ent/pull/546
https://github.com/lolopinto/ent/pull/547
and some fixes
* squash wasn't exposed to CLI
* squash arg needed to be converted to int

auto_schema new version

---

internal/tscode/step.go
tsent/cmd/codegen_test.go

fix pattern base query file name is wrong if complex

---

ts/src/schema/field.ts
ts/src/schema/schema_list.test.ts

plus add length(), minLen(), maxLen(), range() methods to list types
fixes https://github.com/lolopinto/ent/issues/539

fix inconsistency in datatypes

---

ts/src/schema/field.ts

found via https://github.com/lolopinto/ent/pull/587

fix nonsensical code in StringField

---

ts/src/schema/field.ts
ts/src/schema/integer_field.test.ts

As the title says. Mostly just copied from `StringField`.

Add min/max options to IntegerField

---

ts/src/index.ts

i failed to mention it in https://github.com/lolopinto/ent/pull/597 and i'm about to release a new version

expose AllowIfViewerIsEntPropertyRule

---

ts/src/core/base.ts
ts/src/core/privacy_base.test.ts

use constants that don't change on each function call.
probably more performant too

Allow(),Deny(), Skip() should be comparable to each other.

---

internal/graphql/ts_templates/index.tmpl

broken by https://github.com/lolopinto/ent/pull/513

fix import of schema in index.ts

---

examples/ent-rsvp/backend/src/ent/generated/address_base.ts
examples/ent-rsvp/backend/src/ent/generated/auth_code_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_data_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_group_base.ts
examples/ent-rsvp/backend/src/ent/generated/user_base.ts
examples/simple/src/ent/generated/address_base.ts
examples/simple/src/ent/generated/auth_code_base.ts
examples/simple/src/ent/generated/comment_base.ts
examples/simple/src/ent/generated/contact_base.ts
examples/simple/src/ent/generated/event_base.ts
examples/simple/src/ent/generated/holiday_base.ts
examples/simple/src/ent/generated/hours_of_operation_base.ts
examples/simple/src/ent/generated/user_base.ts
examples/simple/src/ent/tests/user.test.ts
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
examples/todo-sqlite/src/ent/generated/account_base.ts
examples/todo-sqlite/src/ent/generated/tag_base.ts
examples/todo-sqlite/src/ent/generated/todo_base.ts
internal/tscode/base.tmpl
ts/package-lock.json
ts/src/core/ent.ts
ts/src/core/ent_data.test.ts
ts/src/core/query/assoc_query.ts

https://github.com/lolopinto/ent/issues/616
makes callers better

change generated loadMany API to a Map 

---

python/auto_schema/setup.py

for https://github.com/lolopinto/ent/pull/617

new auto_schema version

---

internal/auto_schema/auto_schema.go
python/auto_schema/auto_schema/cli/__init__.py

fixes https://github.com/lolopinto/ent/issues/624
doesn't do anything with debug mode. will pay attention and see if i miss it

catch auto_schema error and show it in a nicer way

---

python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/setup.py

wasn't working when applied in production. not sure i even want to know what's going on here with try/except

refix https://github.com/lolopinto/ent/pull/653

---

ts/src/action/action.ts
ts/src/action/executor.test.ts
ts/src/action/orchestrator.ts
ts/src/core/ent.ts
ts/src/testutils/builder.ts

we were previously writing default fields such as updated_at
longterm known issue

when editing an object and no fields change, don't write to the database

---

ts/package.json
ts/src/action/experimental_action.ts

for https://github.com/lolopinto/ent/issues/635

updateRawObject and getSimpleEditAction

---

.gitignore
internal/edge/edge.go
internal/field/field_type.go
internal/tsimport/import.go
internal/tsimport/path.go

allow foreign keys of foo_id type

---

examples/simple/src/graphql/mutations/generated/contact/contact_edit_type.ts
examples/simple/src/graphql/mutations/generated/event/event_edit_type.ts
internal/action/action_test.go
internal/field/field.go
internal/field/field_type.go
internal/graphql/generate_ts_code.go
internal/graphql/graphql_fields_test.go

graphql mutations with id fields weren't being saved in the edit mutation.
this fixes that

Fix graphql mutations with field edge

---

ts/packages/ent-graphql-tests/package-lock.json
ts/packages/ent-graphql-tests/package.json
ts/packages/ent-graphql-tests/src/index.ts
ts/packages/ent-graphql-tests/tsconfig.json
ts/src/testutils/ent-graphql-tests/index.ts

once to bump to latest everything. 
another to add nullQueryPaths to `mutationRootConfig`

Update ent-graphql-tests package

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/graphql/mutations/generated/contact/contact_edit_type.ts
examples/simple/src/graphql/mutations/generated/contact_email/contact_email_edit_type.ts
examples/simple/src/graphql/mutations/generated/contact_phone_number/contact_phone_number_edit_type.ts
examples/simple/src/graphql/mutations/generated/event/event_create_type.ts
examples/simple/src/graphql/mutations/generated/event/event_edit_type.ts
examples/simple/src/graphql/tests/event_type.test.ts
internal/action/action.go
internal/action/action_test.go
internal/action/interface.go
internal/enttype/type.go
internal/field/field_type.go
internal/graphql/generate_ts_code.go
internal/graphql/ts_templates/interfaces.tmpl
ts/package.json
ts/src/graphql/index.ts
ts/src/graphql/node_resolver.ts

* id fields in graphql not working for nullable/optional id fields
* passing the wrong field if fieldName != graphqlName e.g. with custom graphqlName
related https://github.com/lolopinto/ent/issues/240

some graphql fixes

---

internal/schema/input/parse_ts.go
tsent/cmd/printschema.go
tsent/cmd/root.go

simple printschema command to confirm what's being parsed

---

docs/docs/actions/permissions.md

docs here are stale since https://github.com/lolopinto/ent/pull/629

update actions/permissions docs

---

ts/package.json
ts/src/core/base.ts
ts/src/core/privacy.test.ts
ts/src/core/privacy.ts

change `DenyWithReason` to take a string to be easier to use

Deny with reason string

---

python/auto_schema/auto_schema/diff.py
python/auto_schema/setup.py
python/auto_schema/tests/runner_test.py
ts/Dockerfile

seemingly broken since https://github.com/lolopinto/ent/pull/408

Fix deleting table with index

---

examples/simple/src/ent/contact/query/contact_to_contact_emails_query.ts
examples/simple/src/ent/contact/query/contact_to_contact_phone_numbers_query.ts

artifacts of https://github.com/lolopinto/ent/pull/683

remove dangling files in example

---

internal/prompt/prompt.go

was reading one rune at a time but was also reading '\n' so if the wrong thing was passed in, ends up displaying multiple error messages
change to read a string and ignore whitespace: ' ', '\n' etc
then check the value of one rune to see if it's what we want

fix logic for reading runes with prompts

---

internal/edge/edge.go
internal/schema/schema_input_test.go
internal/schemaparser/ent_config.go

fixes https://github.com/lolopinto/ent/issues/745

fix properties of inverseFieldEdge not being propagated

---

ts/packages/ent-graphql-tests/package.json
ts/packages/ent-graphql-tests/src/index.ts
ts/packages/ent-graphql-tests/src/test.ts
ts/src/testutils/ent-graphql-tests/index.ts

if an existing endpoint exists with complicated stuff, want to be able to test it

[ent-graphql-tests] add ability to pass custom server and endpoint

---

.github/workflows/python_ci.yml
python/auto_schema/CONTRIBUTING.MD
python/auto_schema/tests/conftest.py
python/auto_schema/tests/runner_test.py

this is what we do we do in go and TS
was making other changes and kept running into issues with this. this simplifies things so no weirdness with connections, transactions etc like we were doing

[auto_schema] change tests to create a new db everytime

---

internal/edge/edge.go
internal/enttype/array_list_test.go
internal/enttype/json_test.go
internal/enttype/type.go
internal/enttype/types_test.go
internal/field/field_type.go
internal/graphql/custom_ts.go
internal/graphql/custom_ts_test.go
internal/graphql/generate_ts_code.go
internal/graphql/renderer.go
internal/graphql/ts_templates/connection.tmpl
internal/graphql/ts_templates/field.tmpl
internal/graphql/ts_templates/field_config.tmpl
internal/graphql/ts_templates/object.tmpl
internal/graphql/ts_templates/render_args.tmpl
internal/graphql/ts_templates/root_query.tmpl
internal/schema/node_data.go
internal/schema/pattern_info.go
internal/tscode/action_base.tmpl
internal/tscode/base.tmpl
internal/tscode/builder.tmpl
internal/tscode/ent_query_base.tmpl
internal/tscode/step.go
internal/tsimport/import_path.go

fixes https://github.com/lolopinto/ent/issues/703
cleaning up technical debt

Import type consolidation

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/tests/user.test.ts
examples/simple/src/ent/user/actions/generated/create_user_action_base.ts
examples/simple/src/graphql/tests/user_type.test.ts
examples/simple/src/schema/user.ts
internal/action/interface.go
internal/field/compare_field.go
internal/field/field_type.go
internal/graphql/generate_ts_code.go
internal/schema/input/input.go
internal/schema/input/parse_ts_test.go
ts/package.json
ts/src/schema/schema.ts

useful for migrations, internal tools, etc

add ability to indicate a field isn't editable in graphql

---

internal/action/compare_action.go
internal/edge/compare_edge.go
internal/field/compare_field.go
internal/schema/change/change.go
internal/schema/compare_schema.go
internal/schema/compare_schema_test.go
internal/schema/enum/enum.go

follow-ups to https://github.com/lolopinto/ent/pull/777

Compare schema updates/fixes

---

internal/codegen/change.go
internal/codegen/prompts.go

change prompts to use Compare schema instead of hitting the db via auto_schema.
everything in the same process much faster than going to the db

Prompts use compare schema

---

internal/codegen/codegen_processor.go
internal/codegen/config.go
internal/tscode/step.go
tsent/cmd/codegen.go
tsent/cmd/codegen_test.go
tsent/cmd/delete_schema.go
tsent/cmd/root.go

follow-up to https://github.com/lolopinto/ent/pull/783

write-all flag to force all files to be written in case there's a bug

---

internal/build_info/build_info.go
internal/codegen/codegen_processor.go
internal/codegen/config.go
internal/util/os.go
tsent/cmd/codegen.go
tsent/main.go

build_info to force writing everything if in dev environment or if things changed since last build
anytime there's new codegen or docker version, we'll pay a one time cost of writing all the files since no idea what may have changed

build info

---

internal/schema/enum/enum.go

fix enums comparison

---

internal/graphql/generate_ts_code.go

instead of doing each search on its own as we were currently doing

rg supports a regex which means we can search for all things at once

---

internal/graphql/custom_ts.go
internal/graphql/generate_ts_code.go
internal/util/script_file.go
tsent/cmd/print_custom_schema.go
tsent/cmd/root.go

like https://github.com/lolopinto/ent/pull/704 but for custom graphql schema
helpful for debugging and for ish like https://github.com/lolopinto/ent/issues/792

print_custom_schema command

---

internal/codegen/codegen_processor.go
internal/schema/compare_schema.go
internal/schema/compare_schema_test.go

was comparing wrong strings 
+ adding a node which also has edges or actions wasn't processing actions

[bugfix|cli] Fix adding new node 

---

tsent/cmd/delete_schema.go

* pass write all flag to codegen
* delete query file if it exists

delete_schema fixes

---

docs/docs/advanced-topics/running-locally.md
release_image/main.go
ts/Dockerfile
ts/Dockerfile.tmpl
ts/package-lock.json

productionizing https://github.com/lolopinto/ent/pull/749

new release

---

internal/build_info/build_info.go

if modified, regenerate everything since there's codegen directives which could affect lots of files

check time ent.yml was last modified in build_info

---

internal/edge/compare_edge.go
internal/file/delete_file.go
internal/graphql/custom_data.go
internal/graphql/generate_ts_code.go
internal/schema/change/change.go
internal/schema/compare_schema_test.go
internal/tscode/step.go
internal/tscode/write_action.go

addresses part of https://github.com/lolopinto/ent/issues/556
handles deleting edge, action, graphql connection, mutation, custom queries, custom mutations

use compare schema info to delete files if we detect changes

---

ts/package-lock.json
ts/package.json

update minimist to the latest version

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package.json
ts/packages/ent-email/package-lock.json
ts/packages/ent-email/package.json
ts/packages/ent-graphql-tests/package-lock.json
ts/packages/ent-graphql-tests/package.json
ts/packages/ent-passport/package-lock.json
ts/packages/ent-passport/package.json
ts/packages/ent-password/package-lock.json
ts/packages/ent-password/package.json
ts/packages/ent-phonenumber/package-lock.json
ts/packages/ent-phonenumber/package.json

for https://github.com/lolopinto/ent/pull/827 and https://github.com/lolopinto/ent/pull/825
also updates all dependencies

new ts version

---

ts/package.json
ts/src/action/action.ts

fix some type ish. was getting errors using BaseAction.bulkAction the other way
didn't push after making these changes and almost missed them

followup to https://github.com/lolopinto/ent/pull/830

---

python/auto_schema/auto_schema/config.py
python/auto_schema/auto_schema/ops_impl.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/tests/ops_sql_test.py

construct sql queries manually instead of using sqlalchemy magic methods

auto_schema changes to support sql output

---

python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/auto_schema/command.py
python/auto_schema/auto_schema/config.py
python/auto_schema/auto_schema/env.py
python/auto_schema/auto_schema/runner.py

depends on https://github.com/lolopinto/ent/pull/837
* exposes offline support that alembic already: https://alembic.sqlalchemy.org/en/latest/offline.html
e.g. showing sql for most recent change in example: https://github.com/lolopinto/ent/blob/main/examples/simple/src/schema/versions/42b21a3bccc5_2022124213133_add_column_day_of_week_to_table_.py
```sql
LOCAL_AUTO_SCHEMA=true python3 auto_schema/cli/__init__.py -e postgresql://ola:@localhost/tsent_test -s /Users/ola/code/ent/examples/simple/src/schema  --upgrade a5184ce57a3b:42b21a3bccc5 --sql=true
BEGIN;
-- Running upgrade a5184ce57a3b -> 42b21a3bccc5
ALTER TABLE holidays ADD COLUMN day_of_week TEXT NOT NULL;
ALTER TABLE holidays ADD COLUMN day_of_week_alt TEXT;
UPDATE alembic_version SET version_num='42b21a3bccc5' WHERE …
```

[auto_schema] provide a way to get sql output of revisions/changes

---

examples/simple/jest.config.js
examples/simple/src/ent/tests/address.test.ts
examples/simple/src/ent/tests/contact.test.ts
examples/simple/src/ent/tests/event.test.ts
examples/simple/src/ent/tests/hours_of_operations.test.ts
examples/simple/src/ent/tests/user.test.ts
examples/simple/src/ent/tests/user_query.test.ts
examples/simple/src/graphql/mutations/tests/user_mutations.test.ts
examples/simple/src/graphql/tests/bulk_upload_contact.test.ts
examples/simple/src/graphql/tests/contact_type.test.ts
examples/simple/src/graphql/tests/event_type.test.ts
examples/simple/src/graphql/tests/holiday_type.test.ts
examples/simple/src/graphql/tests/hours_of_operation_type.test.ts
examples/simple/src/graphql/tests/user_auth.test.ts
examples/simple/src/graphql/tests/user_auth_jwt.test.ts
examples/simple/src/graphql/tests/user_type.test.ts
examples/simple/src/graphql/tests/viewer_type.test.ts
examples/simple/src/schema/schema.sql
examples/simple/src/testsetup/globalSetup.ts
examples/simple/src/testsetup/globalTeardown.ts
examples/simple/src/testsetup/setup.ts

uses sql file generated from https://github.com/lolopinto/ent/pull/838
it's possible to even have different database for each test file but not used here

update example to use new database created just for that run of tests

---

internal/db/db_schema_test.go

instead of typescript code
this is faster since we don't have to call into different process. internal/schema/input should test the parsing here

[cleanup] change db_schema_test to use input schema 

---

examples/simple/src/testsetup/globalSetup.ts

just pass raw sql to pgclient.query()
followup to https://github.com/lolopinto/ent/pull/840

remove psql dependency in example

---

internal/db/db_schema.go
internal/db/db_schema.tmpl
internal/db/db_schema_test.go
internal/schema/input/compare.go
internal/schema/input/input.go
internal/schema/schema.go
internal/schema/schema_constraints_test.go
python/auto_schema/tests/conftest.py
python/auto_schema/tests/runner_test.py
ts/src/schema/schema.ts

go and ts changes. auto_schema changes previously done at https://github.com/lolopinto/ent/pull/836

integrate full text index into the schema

---

examples/simple/ent.yml
internal/auto_schema/auto_schema.go
internal/codegen/config.go
internal/db/db_schema.go
python/auto_schema/auto_schema/cli/__init__.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/setup.py
ts/src/core/config.ts

followup to https://github.com/lolopinto/ent/pull/838/files
forgot that when no database is passed, defaults to database with same name as user. may work on local db but not elsewhere
also, noticed a warning from https://github.com/lolopinto/ent/pull/849 and created https://github.com/lolopinto/ent/issues/852

auto_schema: take optional empty_database for all_sql comparison

---

ts/package.json
ts/src/core/clause.test.ts
ts/src/core/clause.ts
ts/src/index.ts

needed for columns which aren't tsvector

more clauses for querying full text columns

---

internal/schema/schema.go
internal/schema/schema_constraints_test.go

ran into this when i had the wrong column name in an index

validate index columns

---

internal/schema/change/change.go
internal/schema/compare_schema.go
internal/schema/compare_schema_test.go
internal/schema/input/compare.go

this was missing in the original compare schema work which was done a while back
the only place this matters is checking for db changes and that blames to https://github.com/lolopinto/ent/pull/787

compare indices/constraints in nodes

---

examples/todo-sqlite/src/ent/generated/const.ts
examples/todo-sqlite/src/schema/schema.py
internal/build_info/build_info.go
internal/codegen/codegen_processor.go
tsent/cmd/codegen.go
tsent/cmd/downgrade.go

`downgrade` and `codegen --step` only generate a subset of the schema so next time schema is run, we need to run the entire thing

[codegen] flag some commands as needing write-all next time

---

examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
examples/todo-sqlite/src/graphql/generated/schema.gql
examples/todo-sqlite/src/graphql/resolvers/generated/account_type.ts
internal/field/field_type.go
internal/field/fields_type_test.go
internal/graphql/generate_ts_code.go

we need to make sure that non-nullable fields which have a privacy policy are nullable in graphql 
followup to https://github.com/lolopinto/ent/pull/867, https://github.com/lolopinto/ent/pull/876

fix graphql types for non-nullable fields with field privacy

---

examples/ent-rsvp/backend/src/ent/address/actions/generated/address_builder.ts
examples/ent-rsvp/backend/src/ent/auth_code/actions/generated/auth_code_builder.ts
examples/ent-rsvp/backend/src/ent/event/actions/generated/event_builder.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/event_activity_builder.ts
examples/ent-rsvp/backend/src/ent/guest/actions/generated/guest_builder.ts
examples/ent-rsvp/backend/src/ent/guest_data/actions/generated/guest_data_builder.ts
examples/ent-rsvp/backend/src/ent/guest_group/actions/generated/guest_group_builder.ts
examples/ent-rsvp/backend/src/ent/user/actions/generated/user_builder.ts
examples/simple/src/ent/address/actions/generated/address_builder.ts
examples/simple/src/ent/auth_code/actions/generated/auth_code_builder.ts
examples/simple/src/ent/comment/actions/generated/comment_builder.ts
examples/simple/src/ent/contact/actions/generated/contact_builder.ts
examples/simple/src/ent/contact_email/actions/generated/contact_email_builder.ts
examples/simple/src/ent/contact_phone_number/actions/generated/contact_phone_number_builder.ts
examples/simple/src/ent/event/actions/generated/event_builder.ts
examples/simple/src/ent/holiday/actions/generated/holiday_builder.ts
examples/simple/src/ent/hours_of_operation/actions/generated/hours_of_operation_builder.ts
examples/simple/src/ent/user/actions/generated/user_builder.ts
examples/todo-sqlite/src/ent/account/actions/generated/account_builder.ts
examples/todo-sqlite/src/ent/tag/actions/generated/tag_builder.ts
examples/todo-sqlite/src/ent/todo/actions/generated/todo_builder.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
internal/tscode/builder.tmpl

updateInput just updates the given keys. overrideInput changes the input completely with what was given

generate overrideInput in Builder which is different from updateInput

---

examples/simple/src/ent/contact.ts
internal/field/field_type.go
internal/field/fields_type_test.go
internal/tscode/base.tmpl

since types have changed because of field privacy

make sure right convertXXX function is called

---

internal/field/field_type.go
internal/field/fields_type_test.go
internal/schema/node_data.go

followup to https://github.com/lolopinto/ent/pull/881

make sure that correct convertXXX function is imported

---

.github/testdata/jest.config.js.example
.github/testdata/user.ts.example
.github/testdata/verify_graphql_schema.test.ts.example
.github/workflows/e2e.yml
internal/graphql/generate_ts_code.go
tsent/cmd/codegen_test.go

a series of changes broke it for parsing in ents. top level queries and mutations still working
also added check in e2e test to make sure it's caught next time
fixes https://github.com/lolopinto/ent/issues/883

fix custom graphql parsing

---

examples/ent-rsvp/backend/src/ent/address/actions/generated/address_builder.ts
examples/ent-rsvp/backend/src/ent/auth_code/actions/generated/auth_code_builder.ts
examples/ent-rsvp/backend/src/ent/event/actions/generated/event_builder.ts
examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/event_activity_builder.ts
examples/ent-rsvp/backend/src/ent/guest/actions/generated/guest_builder.ts
examples/ent-rsvp/backend/src/ent/guest_data/actions/generated/guest_data_builder.ts
examples/ent-rsvp/backend/src/ent/guest_group/actions/generated/guest_group_builder.ts
examples/ent-rsvp/backend/src/ent/user/actions/generated/user_builder.ts
examples/simple/src/ent/address/actions/generated/address_builder.ts
examples/simple/src/ent/auth_code/actions/generated/auth_code_builder.ts
examples/simple/src/ent/comment/actions/generated/comment_builder.ts
examples/simple/src/ent/contact/actions/generated/contact_builder.ts
examples/simple/src/ent/contact_email/actions/generated/contact_email_builder.ts
examples/simple/src/ent/contact_phone_number/actions/generated/contact_phone_number_builder.ts
examples/simple/src/ent/event/actions/generated/event_builder.ts
examples/simple/src/ent/holiday/actions/generated/holiday_builder.ts
examples/simple/src/ent/hours_of_operation/actions/generated/hours_of_operation_builder.ts
examples/simple/src/ent/user/actions/generated/user_builder.ts
examples/todo-sqlite/src/ent/account/actions/generated/account_builder.ts
examples/todo-sqlite/src/ent/tag/actions/generated/tag_builder.ts
examples/todo-sqlite/src/ent/todo/actions/generated/todo_builder.ts
internal/tscode/builder.tmpl

typescript doesn't like `string` here so changing to `keyof FooInput`
followup to https://github.com/lolopinto/ent/pull/885

change type of arg to deleteInputKey

---

ts/package.json
ts/src/action/orchestrator.ts

if dev needs to run custom privacy check for some reason during the privacy process

expose API in Orchestrator to get unsafe ent 

---

internal/schema/input/input.go
internal/schema/schema.go

any error generated in fieldInfo and edgeinfo generated should be captured and returned instead of adding to list
also, add fieldName to enum errors in input

random fixes I ran into

---

docs/docs/actions/action-only-fields.md
docs/docs/actions/add-edge-action.md
docs/docs/actions/create-action.md
docs/docs/actions/delete-action.md
docs/docs/actions/edge-group-action.md
docs/docs/actions/edit-action.md
docs/docs/actions/remove-edge-action.md
docs/docs/core-concepts/ent-query.md
docs/docs/custom-graphql/custom-accessors.md
docs/docs/custom-graphql/custom-mutations.md
docs/docs/custom-graphql/custom-queries.md
docs/docs/custom-graphql/file-uploads.md
docs/docs/custom-graphql/gql-arg.md
docs/docs/custom-graphql/gql-field.md
docs/docs/ent-schema/actions.md
docs/docs/intro.mdx

location was changed at https://github.com/lolopinto/ent/pull/513 but this wasn't updated

update some docs to link to correct file

---

internal/graphql/generate_ts_code.go
internal/schema/change/change.go
internal/schema/compare_schema.go
internal/schema/compare_schema_test.go
internal/tscode/step.go

similar to https://github.com/lolopinto/ent/pull/818
fixes https://github.com/lolopinto/ent/issues/871

Delete generated enum files when they no longer apply

---

.github/testdata/schema1.json
.github/testdata/schema2.json
.github/workflows/e2e.yml
tsent/cmd/delete_schema.go
tsent/cmd/root.go

instead of trying to parse the code and create a new schema, just delete the schema from the map we have and rerun codegen
ran manually + add to e2e test
fixes https://github.com/lolopinto/ent/issues/910

fix delete schema command

---

internal/field/field_type.go
internal/schema/node_data.go
internal/schema/pattern_info.go

followup to https://github.com/lolopinto/ent/pull/912
need to make sure imports for `convertXXX` methods are added

fix mixin imports

---

internal/tscode/step.go

gating code was removed by https://github.com/lolopinto/ent/pull/817

only write builder file if there's actions

---

examples/ent-rsvp/backend/src/ent/generated/address_base.ts
examples/ent-rsvp/backend/src/ent/generated/auth_code_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_data_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_group_base.ts
examples/simple/src/ent/generated/auth_code_base.ts
examples/simple/src/ent/generated/comment_base.ts
examples/simple/src/ent/generated/contact_base.ts
examples/simple/src/ent/generated/contact_email_base.ts
examples/simple/src/ent/generated/contact_phone_number_base.ts
examples/simple/src/ent/generated/event_base.ts
examples/todo-sqlite/src/ent/generated/tag_base.ts
examples/todo-sqlite/src/ent/generated/todo_base.ts
internal/tscode/base.tmpl

to not have async() if they don't need them

change a few generated methods in base class

---

docs/docs/loaders/query-loader.md
internal/schema/node_data.go
internal/tscode/ent_query_base.tmpl
internal/tscode/loaders.tmpl

update const in `loaders.ts`. seen in todo when that's converted (not included)

Update schema const

---

ts/package.json
ts/src/schema/schema.ts
ts/src/tsc/move_generated.ts

fix prettier paths + return in path

rando fixes

---

ts/package.json
ts/src/tsc/transform_action.ts

it may not be required
fixes https://github.com/lolopinto/ent/issues/935

add builder to list of new imports in Action

---

examples/ent-rsvp/README.MD
examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/todo-sqlite/README.MD
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
examples/todo-sqlite/src/schema/account.ts
examples/todo-sqlite/src/schema/patterns/base.ts
examples/todo-sqlite/src/schema/tag.ts
examples/todo-sqlite/src/schema/todo.ts
ts/package.json
ts/src/scripts/migrate_v0.1.ts
ts/src/tsc/ast.ts
ts/src/tsc/move_generated.ts
ts/src/tsc/transform.ts
ts/src/tsc/transform_action.ts
ts/src/tsc/transform_schema.ts
tsent/cmd/migrate_v0.1.go
tsent/cmd/root.go

fixes https://github.com/lolopinto/ent/issues/931

Transform schema updates

---

ts/package.json
ts/src/tsc/transform.ts

https://github.com/lolopinto/ent/issues/933

treat require() as import/export

---

examples/simple/src/ent/contact/actions/create_contact_action.ts
examples/simple/src/ent/generated/address/actions/address_builder.ts
examples/simple/src/ent/generated/auth_code/actions/auth_code_builder.ts
examples/simple/src/ent/generated/comment/actions/comment_builder.ts
examples/simple/src/ent/generated/contact/actions/contact_builder.ts
examples/simple/src/ent/generated/contact_email/actions/contact_email_builder.ts
examples/simple/src/ent/generated/contact_phone_number/actions/contact_phone_number_builder.ts
examples/simple/src/ent/generated/event/actions/event_builder.ts
examples/simple/src/ent/generated/holiday/actions/holiday_builder.ts
examples/simple/src/ent/generated/hours_of_operation/actions/hours_of_operation_builder.ts
examples/simple/src/ent/generated/user/actions/user_builder.ts
internal/schema/node_data.go
internal/tscode/builder.tmpl

fixes https://github.com/lolopinto/ent/issues/950 to avoid awkward code in triggers

api to get id in action

---

docs/package-lock.json
docs/package.json

acorn explicitly for docs

---

examples/simple/src/ent/generated/auth_code_base.ts
examples/simple/src/ent/generated/comment_base.ts
examples/simple/src/ent/generated/contact_base.ts
examples/simple/src/ent/generated/contact_email_base.ts
examples/simple/src/ent/generated/contact_phone_number_base.ts
examples/simple/src/ent/generated/event_base.ts
internal/tscode/base.tmpl
internal/tscode/interface.tmpl

add back check removed from https://github.com/lolopinto/ent/pull/973 and followup to https://github.com/lolopinto/ent/pull/972

more fixes

---

ts/package.json
ts/src/tsc/transform_action.ts

followup to https://github.com/lolopinto/ent/pull/978

change getTriggers, getObservers, getValidators type in migration

---

examples/ent-rsvp/backend/src/ent/generated/address/actions/address_builder.ts
examples/ent-rsvp/backend/src/ent/generated/auth_code/actions/auth_code_builder.ts
examples/ent-rsvp/backend/src/ent/generated/event/actions/event_builder.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity/actions/event_activity_builder.ts
examples/ent-rsvp/backend/src/ent/generated/guest/actions/guest_builder.ts
examples/ent-rsvp/backend/src/ent/generated/guest_data/actions/guest_data_builder.ts
examples/ent-rsvp/backend/src/ent/generated/guest_group/actions/guest_group_builder.ts
examples/ent-rsvp/backend/src/ent/generated/user/actions/user_builder.ts
examples/simple/src/ent/generated/address/actions/address_builder.ts
examples/simple/src/ent/generated/auth_code/actions/auth_code_builder.ts
examples/simple/src/ent/generated/comment/actions/comment_builder.ts
examples/simple/src/ent/generated/contact/actions/contact_builder.ts
examples/simple/src/ent/generated/contact_email/actions/contact_email_builder.ts
examples/simple/src/ent/generated/contact_phone_number/actions/contact_phone_number_builder.ts
examples/simple/src/ent/generated/event/actions/event_builder.ts
examples/simple/src/ent/generated/holiday/actions/holiday_builder.ts
examples/simple/src/ent/generated/hours_of_operation/actions/hours_of_operation_builder.ts
examples/simple/src/ent/generated/user/actions/user_builder.ts
examples/todo-sqlite/src/ent/generated/account/actions/account_builder.ts
examples/todo-sqlite/src/ent/generated/tag/actions/tag_builder.ts
examples/todo-sqlite/src/ent/generated/todo/actions/todo_builder.ts
internal/tscode/builder.tmpl

fixes https://github.com/lolopinto/ent/issues/519

fix typing of fields in builder

---

internal/db/db_schema_test.go
internal/edge/edge.go
internal/field/field_type.go
internal/schema/schema.go
internal/schema/schema_input_test.go

fixes https://github.com/lolopinto/ent/issues/951, https://github.com/lolopinto/ent/issues/872

validate fieldEdge.schema

---

internal/field/compare_field.go
internal/schema/compare_schema_test.go

...as modify field instead of remove+add
fixes https://github.com/lolopinto/ent/issues/889

flag changes where field changed but storage key didn't 

---

ts/package.json
ts/src/action/action.ts
ts/src/action/orchestrator.ts

fixes https://github.com/lolopinto/ent/issues/701

pass context to Action.viewerForEntLoad

---

ts/package.json
ts/src/core/loaders/object_loader.test.ts
ts/src/core/loaders/object_loader.ts

fix bug with object loader

---

ts/package.json
ts/src/schema/struct_field.test.ts
ts/src/schema/struct_field.ts

revert https://github.com/lolopinto/ent/pull/986
can't do this because of mismatch of keys
from https://github.com/lolopinto/ent/issues/921:
```
TODO: what should we store wrt these fields? e.g. lowerCase or storage_key. Would need a format and an unformatting
```

Revert struct type changes

---

docs/docs/advanced-topics/cli.md
tsent/cmd/alembic.go
tsent/cmd/codegen.go
tsent/cmd/detect_dangling.go
tsent/cmd/root.go

plus some small changes in commands
fixes https://github.com/lolopinto/ent/issues/747

update CLI docs

---

internal/schema/compare_schema.go
internal/schema/compare_schema_test.go

fixes https://github.com/lolopinto/ent/issues/963
handle enums with no graphql component
this code is terrible

fix null error

---

examples/ent-rsvp/ent-rsvp-web/next-env.d.ts
examples/ent-rsvp/ent-rsvp-web/package-lock.json
examples/ent-rsvp/ent-rsvp-web/pages/events/[eventSlug].tsx
examples/ent-rsvp/ent-rsvp-web/pages/events/[eventSlug]/rsvp.tsx
examples/ent-rsvp/ent-rsvp-web/schema.graphql
examples/ent-rsvp/ent-rsvp-web/src/__generated__/addressEditMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/eventActivityAddInviteMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/eventActivityDeleteMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/eventActivityEditMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/eventActivityRemoveInviteMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/eventActivityRsvpStatusEditMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/guestEditMutation.graphql.ts
examples/ent-rsvp/ent-rsvp-web/src/__generated__/guestGroupDeleteMutation.graphql.ts

to reference changes in https://github.com/lolopinto/ent/pull/1011

update ent-rsvp-web 

---

examples/ent-rsvp/backend/develop.Dockerfile
examples/simple/develop.Dockerfile
examples/todo-sqlite/develop.Dockerfile

update develop.Dockerfile to point to latest images

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package-lock.json
ts/package.json
ts/src/action/executor.test.ts
ts/src/action/executor.ts
ts/src/action/experimental_action.ts
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/testutils/builder.ts

adds `Orchestrator.validWithErrors` to get validation errors + `Orchestrator.getValidatedFields` to get data to write to db
also, adds some typing changes to make things work

new action APIs

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/schema/user_schema.ts
ts/package.json
ts/src/schema/schema.ts

to allow for other keys if developers want to store extra info in the schema

flexible TypeScript interfaces

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/tests/contact.test.ts
ts/package.json
ts/src/core/clause.test.ts
ts/src/core/clause.ts
ts/src/core/db_clause.test.ts
ts/src/index.ts

new function to expose a new array operator
https://github.com/lolopinto/ent/pull/1031

q.PostgresArrayOverlaps

---

internal/build_info/build_info.go
tsent/cmd/codegen.go
tsent/cmd/root.go
tsent/cmd/upgrade.go

calls it in go and doesn't affect auto-schema
fixes https://github.com/lolopinto/ent/issues/991

codegen calls upgrade

---

ts/package.json
ts/src/core/privacy.ts

have been meaning to do this for a while, doing it now

change how privacy rules are evaluated

---

examples/simple/package-lock.json
examples/simple/package.json
ts/package.json

followup to https://github.com/lolopinto/ent/pull/1052

new version

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/generated/user_base.ts
internal/tscode/base.tmpl
internal/tscode/mixin.tmpl
internal/tscode/step.go
ts/package.json
ts/src/schema/schema.ts

followup to https://github.com/lolopinto/ent/pull/1052 and https://github.com/lolopinto/ent/pull/1052

Fix convert + version

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/graphql/tests/time_diff.test.ts
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package.json

for https://github.com/lolopinto/ent/pull/1061 and https://github.com/lolopinto/ent/pull/1062

new version + update examples

---

examples/simple/src/ent/generated/user_base.ts
examples/simple/src/ent/tests/user.test.ts
examples/simple/src/ent/user/actions/create_user_action.ts
examples/simple/src/viewer/viewer.ts
internal/tscode/base.tmpl
ts/src/core/loaders/object_loader.test.ts
ts/src/core/loaders/object_loader.ts

followup to https://github.com/lolopinto/ent/pull/1065

ondemand fields followup

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package.json
ts/src/core/ent.ts
ts/src/core/ent_db_errors.test.ts
ts/src/core/privacy.ts
ts/src/schema/schema_json.test.ts
ts/src/schema/schema_list.test.ts
ts/src/testutils/db_mock.test.ts

fixes https://github.com/lolopinto/ent/issues/862

stop swallowing db errors

---

ts/src/core/clause.test.ts
ts/src/core/clause.ts
ts/src/core/db_clause.test.ts

incorrect values makes it harder to debug when there's query issues

Change clause log values for a couple

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/graphql/tests/hours_of_operation_type.test.ts
ts/package.json
ts/src/schema/postgres_schema_live.test.ts
ts/src/testutils/db_time_zone.ts

instead of assuming the local timezone and db timezone are the same
fixes https://github.com/lolopinto/ent/issues/557

fix (local) timezone tests when traveling by taking info from db

---

ts/package.json
ts/src/schema/field.ts
ts/src/testutils/db/fixture.ts
ts/src/testutils/db/value.test.ts
ts/src/testutils/db/value.ts

take the logic that was in `ent-explore-schema` and update it for almost all types
https://github.com/lolopinto/ent-explore-schema/blob/main/src/value.test.ts
https://github.com/lolopinto/ent-explore-schema/blob/main/src/value.ts

test fixtures setup v0

---

examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/packages/ent-soft-delete/package-lock.json
ts/packages/ent-soft-delete/package.json
ts/packages/ent-soft-delete/src/soft_delete.ts

types were chanegd and I failed to update this

update soft delete pattern and new version

---

ts/package.json
ts/src/core/ent.test.ts
ts/src/core/ent.ts

was calling the wrong API and there was no test for it so missed the issue
followup to https://github.com/lolopinto/ent/pull/1092

fix loadEntXViaKey

---

examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/todo-sqlite/src/ent/generated/tag/actions/create_tag_action_base.ts
examples/todo-sqlite/src/ent/tag/actions/create_tag_action.ts
examples/todo-sqlite/src/graphql/generated/mutations/tag/create_tag_type.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
examples/todo-sqlite/src/graphql/tests/tag.test.ts
examples/todo-sqlite/src/schema/tag_schema.ts
internal/enttype/type.go
internal/field/field_type.go
internal/field/fields_type_test.go
internal/graphql/generate_ts_code.go
internal/tsimport/import_path.go

fixes https://github.com/lolopinto/ent/issues/1085

fix optional field in action is not respected in codegen for graphql mutation

---

internal/codegen/codegen_processor.go
internal/field/compare_field.go
internal/schema/compare_schema.go
internal/schema/compare_schema_test.go

fixes https://github.com/lolopinto/ent/issues/804

error changing type of field

---

internal/schema/enum/enum.go
internal/schema/enum/enum_test.go
internal/schema/schema.go

fixes https://github.com/lolopinto/ent/issues/1043
we currently validate in TypeScript but not go https://github.com/lolopinto/ent/blob/main/ts/src/schema/enum_field.test.ts#L347-L356

validate enum in schema

---

ts/src/action/action.ts
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts

fix https://github.com/lolopinto/ent/issues/1027

Fix Action.valid

---

internal/codegen/change.go
internal/codegen/prompts.go
internal/schema/input/compare.go
internal/schema/input/compare_test.go
python/auto_schema/auto_schema/diff.py
python/auto_schema/tests/runner_test.py

fixes https://github.com/lolopinto/ent/issues/1030

add prompt confirming index type change

---

internal/schema/change/change.go
internal/schema/input/compare.go
internal/schema/input/compare_test.go
internal/schema/input/input.go

audited last few months of changes

update input to compare for some missing fields

---

python/auto_schema/auto_schema/runner.py
python/auto_schema/setup.py

wasn't relevant. could just run it with sqlite and it worked

[auto_schema] remove dialect check in all_sql

---

ts/src/schema/postgres_schema_live.test.ts

can't remember why i created this task but seems fine?
fixes #958

test for #958

---

ts/src/core/ent_logs.test.ts

fixes https://github.com/lolopinto/ent/issues/954

test for #954

---

ent/config/config.go
internal/db/db_schema_test.go
internal/file/writer.go
internal/graphql/custom_ts_test.go
internal/schema/testhelper/test_helper.go
internal/schemaparser/interface.go
tsent/cmd/codegen_test.go

ioutil is deprecated https://pkg.go.dev/io/ioutil

deprecate ioutil for io or os packages

---

examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package-lock.json
ts/package.json
ts/src/scripts/custom_compiler.ts

not sure what happened here but broke e2e and slowed down a bunch of changes
first seen in https://github.com/lolopinto/ent/pull/1139 and https://github.com/lolopinto/ent/pull/1138
pulling into its own PR

update custom compiler

---

tsent/cmd/generateschema/generate.go
tsent/cmd/generateschema/generate_test.go
tsent/cmd/generateschema/schema.tmpl

was going through e2e flow and noticed it was still using old API

update tsent generate to latest API

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/ent/generated/address_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_group_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/guest_query_base.ts
examples/ent-rsvp/backend/src/ent/generated/user_query_base.ts
examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/generated/comment_query_base.ts
examples/simple/src/ent/generated/user_query_base.ts
examples/simple/src/ent/user/query/user_to_contacts_query.ts
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
examples/todo-sqlite/src/ent/account.ts
examples/todo-sqlite/src/ent/generated/account_query_base.ts
internal/tscode/ent_query_base.tmpl
ts/package.json
ts/src/core/query/custom_clause_query.ts
ts/src/core/query/custom_query.ts

change default sort column in custom queries to id instead of created_at
follow-up to https://github.com/lolopinto/ent/pull/1138
and provide an easy way to override it in subclasses

change default sort column

---

internal/schema/input/parse_ts.go

something broke on my machine with swc. need to battle it later

flag to disable swc.

---

.github/workflows/e2e.yml
.github/workflows/go_ci.yml
examples/ent-rsvp/backend/src/graphql/generated/mutations/email_available_type.ts
examples/ent-rsvp/backend/src/graphql/generated/mutations/import_guests_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/email_available_query_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/event_query_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/event_slug_available_query_type.ts
examples/simple/src/graphql/generated/mutations/bulk_upload_contact_type.ts
examples/simple/src/graphql/generated/resolvers/time_diff_query_type.ts
examples/todo-sqlite/src/graphql/generated/mutations/mark_all_todos_as_type.ts
examples/todo-sqlite/src/graphql/generated/mutations/remove_completed_todos_type.ts
examples/todo-sqlite/src/graphql/generated/resolvers/closed_todos_last_day_query_type.ts
examples/todo-sqlite/src/graphql/generated/resolvers/open_todos_plural_query_type.ts
examples/todo-sqlite/src/graphql/generated/resolvers/open_todos_query_type.ts
internal/graphql/custom_data.go
internal/graphql/custom_data_test.go
internal/graphql/custom_ts.go
internal/graphql/custom_ts_test.go
internal/graphql/generate_ts_code.go

* capitalize generated graphql interface 
* add first, after, before, last to graphql interface 
* change json encoding to CustomField to inline connection logic

Random custom type changes

---

ts/packages/ent-passport/package-lock.json
ts/packages/ent-passport/package.json

ent-passport update

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/graphql/generated/mutations/import_guests_type.ts

can't update graphql-upload because commonjs vs esm holy war happening

update backend to latest. 

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/ent-rsvp/backend/src/schema/address_schema.ts
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
internal/edge/edge.go
internal/graphql/generate_ts_code.go
internal/tscode/base.tmpl
ts/package.json
ts/src/schema/field.ts
ts/src/schema/uuid_field.test.ts

don't create enum for generated type. just use string type which validates it. be more flexible in terms of values allowed to make it easier for data coming from other clients
fixes https://github.com/lolopinto/ent/issues/625 
fixes https://github.com/lolopinto/ent/issues/1082

Polymorphic type changes

---

internal/action/action_test.go
internal/action/compare_action_test.go
internal/action/interface.go
internal/edge/edge.go
internal/graphql/custom_ts.go
internal/graphql/generate_ts_code.go
internal/schema/customtype/ci_test.go
internal/schema/customtype/custom_interface.go
internal/schema/customtype/custom_union.go
internal/schema/enum/enum.go
internal/schema/node_data.go
internal/schema/schema.go
internal/schema/schema_input_test.go
internal/schema/schema_struct_fields_test.go

fixes https://github.com/lolopinto/ent/issues/1119

better error message if graphql name conflicts

---

examples/simple/src/graphql/generated/schema.gql
examples/simple/src/graphql/generated/schema.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
examples/todo-sqlite/src/graphql/generated/schema.ts
internal/graphql/generate_ts_code.go

followup to https://github.com/lolopinto/ent/pull/947
somehow missed it above
part of addressing https://github.com/lolopinto/ent/issues/921

custom input types missing in schema.gql

---

internal/action/action_test.go

remove dependency on go parsing and internal/testdata/models/configs

cleanup action_test.go

---

internal/action/action_test.go
internal/edge/compare_edge.go
internal/edge/compare_edge_test.go
internal/edge/edge.go
internal/edge/edge_test.go
internal/edge/helper_test.go
internal/schema/input/parse_ts.go
internal/testingutils/testmodel/schema.go

followup to https://github.com/lolopinto/ent/pull/1165

cleanup edge_test

---

internal/db/db_schema_test.go
internal/testingutils/testmodel/schema.go

followup to https://github.com/lolopinto/ent/pull/1165 and https://github.com/lolopinto/ent/pull/1166

db schema cleanup

---

internal/edge/edge.go
internal/schema/schema_input_test.go

fixes https://github.com/lolopinto/ent/issues/697

Better error message for two fields with the same foreignKey definition

---

internal/field/field.go
internal/schema/schema.go

fixes https://github.com/lolopinto/ent/issues/1086

trying to change a field to nullable that has an optionalField in the action gives error

---

examples/simple/ent.yml
examples/simple/src/ent/internal.ts
examples/simple/src/ent/user.ts
examples/simple/src/global_augment.ts
internal/codegen/config.go
internal/tscode/internal.tmpl
internal/tscode/step.go
internal/tsimport/import.go
internal/tsimport/import_path.go
internal/tsimport/import_test.go
ts/src/core/config.ts

make it possible to add a path that's included in `src/ent/internal`
fixes underlying issue in https://github.com/lolopinto/ent/issues/637

support global augmentation

---

internal/action/action_test.go
internal/field/fields_test.go
internal/graphql/custom_ts_test.go
internal/graphql/graphql_fields_test.go
internal/schema/input/parse_ts.go
internal/schema/input/parse_ts_constraints_test.go
internal/schema/input/parse_ts_field_test.go
internal/schema/input/parse_ts_patterns_test.go
internal/schema/schema_constraints_test.go

to not use deprecated typescript APIs

cleanup a bunch of go tests

---

internal/action/action_test.go
internal/codegen/nodeinfo/node_info.go
internal/codegen/prompts.go
internal/db/db_schema_test.go
internal/edge/compare_edge.go
internal/edge/edge.go
internal/edge/edge_test.go
internal/edge/ent_config.go
internal/field/field.go
internal/field/fields_test.go
internal/graphql/graphql_fields_test.go
internal/schema/compare_schema.go
internal/schema/compare_schema_test.go
internal/schema/input/parse_ts.go
internal/schema/node_map.go
internal/schema/schema.go
internal/schema/schema_constraints_test.go
internal/schema/schema_edge_test.go
internal/schema/schema_global_schema_test.go
internal/schema/schema_input_test.go
internal/schema/schema_overrides_test.go
internal/schema/schema_struct_fields_test.go
internal/schema/schema_test.go
internal/testingutils/testmodel/schema.go

remove *Config in internal schema representation

more schema cleanup

---

internal/action/interface.go
internal/graphql/custom_data.go
internal/graphql/generate_ts_code.go

fixes the issue i was seeing in https://github.com/lolopinto/ent/issues/1177
fixes https://github.com/lolopinto/ent/issues/1060

    fix root connections not being written consistently

---

internal/action/action.go
internal/action/action_types.go

fixes https://github.com/lolopinto/ent/issues/997

better error message when referencing invalid field in action

---

internal/graphql/generate_ts_code.go

followup to https://github.com/lolopinto/ent/pull/1212

fix previous

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package.json
ts/src/core/loaders/assoc_edge_loader.ts

will write missing test for this later

ensure that window function query respects soft delete

---

ts/src/core/loaders/assoc_count_loader.test.ts
ts/src/core/loaders/assoc_edge_loader.test.ts

followup to https://github.com/lolopinto/ent/pull/1221

test for https://github.com/lolopinto/ent/pull/1221

---

internal/codegen/codegen_processor.go
internal/codegen/codegenapi/api.go
internal/codegen/config.go
internal/file/delete_file.go
internal/file/writer.go
tsent/cmd/codegen.go
tsent/cmd/delete_schema.go
tsent/cmd/root.go

the files being logged in `--debug` isn't that helpful so moving it to different flag

add --debug-files-mode to cli 

---

examples/todo-sqlite/src/ent/internal.ts
internal/action/interface.go
internal/schema/customtype/custom_interface.go
internal/tscode/interface.tmpl

followup to https://github.com/lolopinto/ent/pull/1236
noticed it while fixing something else

cleanup imports for custom interfaces

---

ts/packages/ent-email/package-lock.json
ts/packages/ent-email/package.json
ts/packages/ent-email/src/email.test.ts

hasn't been updated in a while. bump everything

Update ent email

---

examples/ent-rsvp/backend/jest.config.js
examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/tsconfig.json
examples/simple/jest.config.js
examples/simple/package-lock.json
examples/simple/package.json
examples/simple/tsconfig.json
ts/jest.config.js
ts/package-lock.json
ts/package.json
ts/packages/ent-graphql-tests/package-lock.json
ts/packages/ent-graphql-tests/package.json
ts/packages/ent-graphql-tests/tsconfig.json
ts/tsconfig.json

looks like it was "dead" and came back to life https://github.com/mattphillips/jest-expect-message/issues/47

update to latest jest-expect-message everywhere

---

ts/src/schema/base_schema.ts
ts/src/schema/schema.ts
ts/src/testutils/db/value.test.ts

fixes https://github.com/lolopinto/ent/issues/1265

schema.fields: FieldMap instead of Field[]

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
ts/packages/ent-passport/package-lock.json
ts/packages/ent-passport/package.json

bump ent-passport to get latest jsonwebtoken

---

ts/src/schema/schema.ts

followup to https://github.com/lolopinto/ent/pull/1272
forgot about Patterns and this function which was the original impetus

more fields cleanup

---

.github/workflows/e2e.yml
.github/workflows/go_ci.yml
.github/workflows/node.js.yml
.github/workflows/python_ci.yml
python/auto_schema/auto_schema/env.py
ts/src/core/db.ts

bump postgres images + attempt to set max_connections for nodejs image to `200`

bump postgres images in CI

---

ts/packages/ent-passport/package-lock.json
ts/packages/ent-passport/src/passport.test.ts
ts/packages/ent-passport/src/passport.ts
ts/src/action/executor.test.ts
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator_edge.test.ts
ts/src/action/trigger_priority.test.ts
ts/src/core/db.ts
ts/src/core/ent_data.test.ts
ts/src/core/ent_logs.test.ts
ts/src/core/loaders/object_loader.test.ts
ts/src/core/privacy.test.ts
ts/src/graphql/node_resolver.test.ts
ts/src/graphql/query/shared_edge_connection.ts
ts/src/schema/uuid_field.test.ts
ts/src/testutils/db/temp_db.ts
ts/src/testutils/db_mock.ts

shouldn't be using this anymore and continued usage was blocking other things

delete usecases of QueryRecorder in tests. 

---

ts/package.json
ts/src/action/action.test.ts
ts/src/action/executor.test.ts
ts/src/action/executor.ts
ts/src/action/experimental_action.ts
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/action/transaction.test.ts
ts/src/action/transaction.ts
ts/src/core/base.ts
ts/src/core/db.ts
ts/src/core/ent.ts
ts/src/testutils/action/complex_schemas.ts
ts/src/testutils/db_mock.ts

will replace `BaseAction.bulkAction` is deprecated and call callsites in repo will be converted eventually

Explicit API for Transactions

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/user.ts
examples/simple/src/graphql/generated/resolvers/user_type.ts
examples/simple/src/graphql/generated/schema.gql
examples/simple/src/graphql/tests/user_type.test.ts
examples/simple/src/schema/custom_graphql.json
internal/graphql/custom_ts.go
ts/src/graphql/graphql.ts

fixes https://github.com/lolopinto/ent/issues/1281
uses https://github.com/lolopinto/ent/pull/1303

fix field arguments in custom accessors in an ent node

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/user.ts
examples/simple/src/graphql/generated/resolvers/user_type.ts
examples/simple/src/graphql/generated/schema.gql
examples/simple/src/schema/custom_graphql.json
internal/graphql/custom_data.go
internal/graphql/custom_ts.go
internal/graphql/generate_ts_code.go
ts/package.json
ts/src/scripts/custom_graphql.ts

was supported but wasn't threaded all the way
addresses https://github.com/lolopinto/ent/issues/1297

thread descriptions for custom graphql fields down

---

ts/src/core/config.ts
ts/src/core/ent.ts
ts/src/core/ent_errors.test.ts

addresses https://github.com/lolopinto/ent/issues/1305

option to log sql query when there's a db error

---

python/auto_schema/setup.py

for https://github.com/lolopinto/ent/pull/1329 and https://github.com/lolopinto/ent/pull/1330

new auto_schema

---

examples/simple/src/graphql/generated/resolvers/user/user_to_likes_connection_type.ts
internal/graphql/custom_ts.go

followup to example like https://github.com/lolopinto/ent/pull/1341

fix edge inline functions

---

examples/simple/package-lock.json
examples/simple/package.json
ts/package.json
ts/src/scripts/custom_graphql.ts

followup to https://github.com/lolopinto/ent/pull/1338

use swc for dynamic custom graphql script

---

ts/package.json
ts/src/parse_schema/parse.ts
ts/src/schema/index.ts

seeing nullable = "true" here in some scenarios so handling that

handle weirdness i'm seeing

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/packages/ent-graphql-tests/package.json
ts/packages/ent-graphql-tests/src/index.ts
ts/packages/ent-graphql-tests/src/test.ts
ts/src/testutils/ent-graphql-tests/index.ts

support querying object|list from types which return lists
same for nested objects in mutations

more ent-graphql-tests fixes|upgrades

---

ts/src/schema/json_field.ts
ts/src/schema/schema_json.test.ts

when nested in say a struct field, we wanna stringify just once

don't json.stringify nested json.

---

internal/schema/node_data.go
internal/tscode/base.tmpl

followup to https://github.com/lolopinto/ent/pull/1382
issue if field is nullable and onentload, we end up with errors

followup fix

---

examples/simple/src/ent/generated/user/actions/edit_user_all_fields_action_base.ts
examples/todo-sqlite/src/ent/generated/account/actions/account_update_balance_action_base.ts
examples/todo-sqlite/src/ent/generated/todo/actions/change_todo_bounty_action_base.ts
internal/tscode/action_base.tmpl

followup to https://github.com/lolopinto/ent/pull/1393

---

.vscode/settings.json
ts/src/parse_schema/parse.ts

swap name and destructuring here
fixes https://github.com/lolopinto/ent/issues/1384

fix issue that was only showing up with swc

---

ts/package.json
ts/src/graphql/graphql.ts

like the `JSON` change added in https://github.com/lolopinto/ent/pull/1405

support Ent in custom graphql

---

examples/simple/src/graphql/generated/resolvers/contact_item_result_type.ts
examples/simple/src/graphql/generated/resolvers/user_super_nested_object_type.ts
internal/graphql/ts_templates/object.tmpl

could have circular dependencies and lead to sadness
followup to https://github.com/lolopinto/ent/pull/1410

use a thunk for types of a union

---

.github/testdata/user.ts.example
examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/contact.ts
examples/simple/src/ent/contact_item.ts
examples/simple/src/ent/user.ts
examples/simple/src/ent/user/query/user_to_likes_query.ts
examples/simple/src/graphql/mutations/auth.ts
examples/simple/src/graphql/mutations/import_contact.ts
examples/simple/src/graphql/resolvers/gql_viewer.ts
examples/simple/src/graphql/resolvers/viewer.ts
examples/simple/src/graphql/tests/viewer_type.test.ts
internal/graphql/custom_ts_test.go
ts/package.json
ts/src/graphql/graphql.test.ts
ts/src/graphql/graphql.ts
ts/src/graphql/graphql_custom.test.ts
ts/src/imports/dataz/example1/_auth.ts
ts/src/imports/dataz/example1/_viewer.ts

when using `gqlMutation()` or `gqlQuery`, weird to use `nodeName` when there's no node

change nodeName to class in gqlField()

---

ts/src/graphql/graphql.ts

make name required in gqlFieldArg 

---

ts/package.json
ts/src/action/executor.ts
ts/src/action/orchestrator.test.ts

test observer logic + catch errors when each observer runs so that one error doesn't stop the whole thing
makes the question being asked here moot https://github.com/lolopinto/ent/issues/1427

Small observer change

---

internal/graphql/custom_ts.go
internal/graphql/generate_ts_code.go
tsent/cmd/codegen_test.go

right now, we're not checking for duplicate fields and the error ends up showing up via a broken generated graphql typescript file.
this does the check so it's hopefully clearer if there are issues

check for duplicate graphql fields

---

internal/enttype/type.go
internal/schema/schema.go
internal/schema/schema_constraints_test.go

only string based columns make sense here
string list may eventually be supported but we're not there yet

validate string type for full text columns

---

internal/schema/schema.go
internal/schema/schema_input_test.go

broken by https://github.com/lolopinto/ent/pull/1452

fix indexed edge with inverse edge

---

examples/simple/src/ent/generated/user/actions/create_user_action_base.ts
internal/edge/edge.go
internal/field/field.go
internal/schema/base/common.go
internal/schema/compare_schema_test.go
internal/schema/node_data.go
internal/schema/schema_input_test.go

more in the https://github.com/lolopinto/ent/issues/674 category

fix generated ent query files if snake_case is used

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/todo-sqlite/src/graphql/generated/resolvers/account_type.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
internal/edge/edge.go
internal/graphql/generate_ts_code.go
internal/schema/input/input.go

if `defaultGraphQLFieldFormat` is set in `ent.yml` to `snake_case`, this field should be `snake_case` instead of `snakeCase`

[breaking change] snake case graphql status enum if snaking case format is on

---

ts/package.json
ts/src/action/operations.ts
ts/src/action/orchestrator.ts
ts/src/action/transformed_orchestrator.test.ts
ts/src/core/viewer.ts

EntChangeset.changesetFromQueries
RawQueryOperation type changes

misc API/typing changes

---

ts/package.json
ts/src/core/config.ts
ts/src/core/ent.ts
ts/src/core/loaders/assoc_edge_loader.test.ts
ts/src/core/loaders/assoc_edge_loader.ts
ts/src/core/loaders/index_loader.test.ts
ts/src/core/loaders/query_loader.test.ts
ts/src/core/loaders/query_loader.ts
ts/src/core/query/custom_clause_query.ts
ts/src/core/query/custom_query.ts
ts/src/core/query/query.ts
ts/src/core/query/shared_assoc_test.ts
ts/src/core/query/shared_test.ts
ts/src/core/query/unique_col_query.test.ts
ts/src/tsc/ast.ts

fixes https://github.com/lolopinto/ent/issues/1430

ability to override default limit for edges and connections

---

ts/src/action/orchestrator_upsert.test.ts

followup to https://github.com/lolopinto/ent/pull/1436

fix test sqlite file

---

ent/config/config.go
ent/config/config_test.go

fixes https://github.com/lolopinto/ent/issues/850

url escape passwords we pass to auto_schema

---

internal/schema/node_data.go

when in a map,the generation wasn't consistent because map keys aren't ordered

have generated types in upsert be determinstic

---

ts/src/schema/schema.ts

followup to https://github.com/lolopinto/ent/pull/1272 can't be a list of fields anymore

remove code accounting for list of of fields

---

ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/schema/schema.ts

this will be performed in addition to an action's perivacyPolicy for each field that has it

ability to set privacy policy for any field while writing

---

ts/package.json
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/schema/schema.ts

which is different from editPrivacyPolicy to be used in create vs edit actions
follow-up to https://github.com/lolopinto/ent/pull/1478

createOnlyOverrideEditPrivacyPolicy 

---

internal/schema/schema.go
internal/schema/schema_input_test.go

doesn't make sense and leads to weird things
addresses https://github.com/lolopinto/ent/issues/1434

don't allow can viewer do for actions hidden from graphql

---

examples/ent-rsvp/backend/src/ent/internal.ts
examples/simple/src/graphql/generated/mutations/user_auth_jwt_type.ts
examples/simple/src/graphql/mutations/auth.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
internal/graphql/custom_ts.go

fixes https://github.com/lolopinto/ent/issues/1397

require custom inputs and objects to be exported

---

examples/todo-sqlite/src/ent/generated/account_query_base.ts
examples/todo-sqlite/src/ent/generated/patterns/todo_container_query_base.ts
examples/todo-sqlite/src/ent/generated/tag_query_base.ts
examples/todo-sqlite/src/ent/generated/todo_query_base.ts
examples/todo-sqlite/src/ent/generated/workspace_query_base.ts
examples/todo-sqlite/src/ent/tests/todo.test.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
internal/schema/input/input.go
internal/schema/schema.go
internal/tscode/ent_query_base.tmpl
ts/src/action/orchestrator_edge_data.test.ts
ts/src/core/base.ts
ts/src/core/ent.ts
ts/src/core/loaders/assoc_count_loader.test.ts
ts/src/core/loaders/assoc_count_loader.ts
ts/src/core/loaders/assoc_edge_loader.test.ts
ts/src/core/loaders/assoc_edge_loader.ts
ts/src/core/query/assoc_query.ts
ts/src/core/query/assoc_query_global.test.ts
ts/src/core/query/assoc_query_sqlite.test.ts
ts/src/core/query/assoc_query_sqlite_global.test.ts
ts/src/core/query/query.ts
ts/src/core/query/shared_assoc_test.ts
ts/src/parse_schema/parse.ts
ts/src/testutils/fake_data/fake_user.ts
ts/src/testutils/fake_data/test_helpers.ts
ts/src/testutils/fake_data/user_query.ts

addresses part of https://github.com/lolopinto/ent/issues/1032

API to get deleted edges if transformed edge read/write exists

---

ts/src/core/context.ts
ts/src/core/ent.ts
ts/src/core/ent_custom_data.test.ts
ts/src/core/loaders/assoc_edge_loader.test.ts
ts/src/core/loaders/assoc_edge_loader.ts
ts/src/core/loaders/index_loader.test.ts
ts/src/core/loaders/index_loader.ts
ts/src/core/loaders/query_loader.test.ts
ts/src/core/loaders/query_loader.ts
ts/src/core/query/assoc_query.test.ts
ts/src/core/query/assoc_query_global.test.ts
ts/src/core/query/assoc_query_sqlite.test.ts
ts/src/core/query/assoc_query_sqlite_global.test.ts
ts/src/core/query/complex_custom_query.test.ts
ts/src/core/query/custom_clause_query.ts
ts/src/core/query/custom_query.ts
ts/src/core/query/custom_query_live.test.ts
ts/src/core/query/custom_query_sqlite.test.ts
ts/src/core/query/custom_query_sqlite_global.test.ts
ts/src/core/query/query.ts
ts/src/core/query/shared_test.ts
ts/src/core/query/unique_col_query.test.ts
ts/src/core/query_impl.ts
ts/src/graphql/scalars/orderby_direction.ts
ts/src/testutils/db_mock.test.ts
ts/src/testutils/fake_data/tag_query.ts
ts/src/testutils/fake_data/user_query.ts

follow-up to https://github.com/lolopinto/ent/pull/1504
breaking change for some things

Orderby API cleanup/change

---

examples/simple/src/ent/comment/query/author_to_comments_query.ts
examples/simple/src/ent/comment/query/comment_article_to_comments_query.ts
examples/simple/src/ent/contact/query/contact_comments_from_attachment_query.ts
examples/simple/src/ent/generated/comment_query_base.ts
examples/simple/src/ent/generated/event_query_base.ts
examples/simple/src/ent/generated/user_query_base.ts
examples/simple/src/ent/user/query/user_article_to_comments_query.ts
examples/simple/src/ent/user/query/user_comments_from_attachment_query.ts
examples/simple/src/ent/user/query/user_to_contacts_query.ts
internal/tscode/custom_ent_query.tmpl
internal/tscode/ent_query_base.tmpl
ts/src/index.ts

followup to https://github.com/lolopinto/ent/pull/1507
this will not change non generated code 
it was changed in this example to make sure it works

change generated code to allow new orderby

---

ts/src/action/executor.ts

some cleanups from https://github.com/lolopinto/ent/pull/1436
* removes some TODOs
* changes some nomenclature
* fixes issue with iterator not returning `true` when done
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_generators
"Once created, an iterator object can be iterated explicitly by repeatedly calling next(). Iterating over an iterator is said to consume the iterator, because it is generally only possible to do once. After a terminating value has been yielded additional calls to next() should continue to return {done: true}."
I had thought it could be consumed multiple times which is why there was weirdness 
we don't have any reason to reset so fine as-is. can probably cleanup further by abstracting the iterator into a different class that both …

executor cleanup

---

examples/simple/ent.yml
examples/simple/src/ent/generated/user_base.ts
examples/simple/src/graphql/generated/resolvers/user_type.ts
internal/codegen/config.go
internal/file/writer.go
ts/src/core/config.ts

for example if there's a bug in codegen or a missing feature that hasn't been implemented yet

ability to prevent codegen from overriding a file

---

internal/file/writer.go
release_image/main.go

follow-up to https://github.com/lolopinto/ent/pull/1520

fix rel path check

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/scripts/custom_queries.ts
internal/graphql/custom_ts.go
ts/package.json
ts/src/graphql/graphql.ts
ts/src/schema/schema.ts
ts/src/scripts/custom_graphql.ts

src/scripts/custom_queries using it and much easier to understand what's going on
found a few superfluous things

[cleanup] add a type for when we use custom types so that it's easier to use

---

ts/src/action/orchestrator.ts
ts/src/core/privacy.ts
ts/src/core/query/query.ts
ts/src/schema/field.ts

some privacy changes + some changes to types.isPromise in the future 
shouldn't pass CI till https://github.com/lolopinto/ent/pull/1464 is done...

small async/await changes

---

.github/workflows/go_ci.yml
.github/workflows/node.js.yml
ts/src/schema/postgres_schema_live.test.ts

haven't needed this since we moved to npm

cleanup CI

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/simple/package-lock.json
examples/simple/package.json
examples/todo-sqlite/package-lock.json
examples/todo-sqlite/package.json
ts/package-lock.json
ts/package.json
ts/packages/ent-email/package-lock.json
ts/packages/ent-email/package.json
ts/packages/ent-graphql-tests/package-lock.json
ts/packages/ent-graphql-tests/package.json
ts/packages/ent-passport/package-lock.json
ts/packages/ent-passport/package.json
ts/packages/ent-password/package-lock.json
ts/packages/ent-password/package.json
ts/packages/ent-phonenumber/package-lock.json
ts/packages/ent-phonenumber/package.json
ts/packages/ent-soft-delete/package-lock.json
ts/packages/ent-soft-delete/package.json

https://github.com/lolopinto/ent/issues/1019

v0.1rc before v0.1 release

---

tsent/cmd/downgrade.go

addresses https://github.com/lolopinto/ent/issues/1000
can't automatically update src/schema/schema.py and schema.sql since we can't tell (at least right now) if there have been sensible changes to the schema files and if we need to run codegen again

add a new message after downgrade

---

release_image/main.go

new release for https://github.com/lolopinto/ent/pull/1555

new release 

---

examples/simple/src/graphql/generated/resolvers/contact_date_type.ts
examples/simple/src/graphql/generated/schema.gql
internal/graphql/custom_ts.go

include interfaces in generated custom objects

---

ts/package.json
ts/src/action/action.ts
ts/src/action/operations.ts
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/testutils/builder.ts

helpful if you're logging something and don't want the privacy to lead to issues
may hate it and revert this...

beta|test: actions that can fail silently

---

examples/simple/package-lock.json
examples/simple/package.json
examples/simple/src/ent/tests/contact.test.ts
ts/package.json
ts/src/action/transaction.ts

so that anyone using custom Viewer can use it without type gymanstics

change Transaction API to template Viewer

---

ts/src/core/clause.ts
ts/src/core/db_clause.test.ts

was curious how to query indexed jsonb by columns and here we are

jsonb key check

---

examples/ent-rsvp/backend/package-lock.json
examples/ent-rsvp/backend/package.json
examples/ent-rsvp/backend/src/graphql/generated/resolvers/address_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/event_activity_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/event_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/guest_group_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/guest_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/user_type.ts
examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/ent-rsvp/backend/src/graphql/mutations/auth/auth_types.ts
ts/package.json
ts/src/graphql/graphql.ts

fixes https://github.com/lolopinto/ent/issues/1578

fix nullable: false in custom_graphql not working

---

internal/file/delete_file.go
internal/graphql/custom_data.go
internal/graphql/generate_ts_code.go

this fixes that
fixes https://github.com/lolopinto/ent/issues/1566
tested by making this change and seeing that the files were deleted
```title="src/schema/holiday_schema.ts"
hideFromGraphQL: true,
```
really need tests for these :(

hiding an object from graphql wasn't deleting the object, mutation, connection files

---

examples/simple/src/graphql/generated/mutations/bulk_upload_contact_type.ts
examples/simple/src/graphql/generated/schema.gql
examples/simple/src/graphql/mutations/import_contact.ts
ts/src/graphql/graphql.test.ts

use Transaction API and fixes from last PR

example cleanup

---

examples/todo-sqlite/ent.yml
examples/todo-sqlite/src/ent/generated/account/actions/delete_account_action_base.ts
examples/todo-sqlite/src/ent/generated/todo/actions/delete_todo_action_base.ts
examples/todo-sqlite/src/ent/generated/workspace/actions/delete_workspace_action_base.ts
examples/todo-sqlite/src/ent/tests/account.test.ts
examples/todo-sqlite/src/ent/tests/todo.test.ts
internal/codegen/config.go
internal/tscode/action_base.tmpl
ts/src/core/config.ts

fixes https://github.com/lolopinto/ent/issues/1591

option to rename saveWithoutTransform methods

---

ts/package.json
ts/src/action/action.test.ts
ts/src/action/operations.ts
ts/src/action/orchestrator_upsert.test.ts
ts/src/core/clause.ts
ts/src/core/db_clause.test.ts
ts/src/core/ent.ts
ts/src/core/ent_data.test.ts
ts/src/core/ent_logs.test.ts
ts/src/core/loaders/assoc_count_loader.test.ts
ts/src/core/loaders/assoc_edge_loader.test.ts
ts/src/core/loaders/object_loader.test.ts
ts/src/core/loaders/query_loader.test.ts
ts/src/core/loaders/raw_count_loader.test.ts
ts/src/core/logger.ts
ts/src/core/query/complex_custom_query.test.ts
ts/src/core/query/unique_col_query.test.ts
ts/src/core/query_impl.ts

addresses https://github.com/lolopinto/ent/issues/1599
similar to https://github.com/lolopinto/ent/pull/1577, querying helpers

query sub fields in a struct list

---

examples/todo-sqlite/src/ent/generated/tag/actions/tag_builder.ts
examples/todo-sqlite/src/ent/generated/tag_base.ts
examples/todo-sqlite/src/schema/tag_schema.ts
internal/field/field.go

fixes https://github.com/lolopinto/ent/issues/1575

fix non-nullable uuid field with privacyPolicy and privacy on demand

---

ts/src/core/clause.ts
ts/src/core/ent.ts
ts/src/core/ent_custom_data.test.ts
ts/src/core/loaders/object_loader.ts
ts/src/core/loaders/query_loader.ts
ts/src/core/query/custom_query.ts

fixes https://github.com/lolopinto/ent/issues/1592

update loadCustom to not add clause if clause with that column is already passed in

---

examples/todo-sqlite/ent.yml
examples/todo-sqlite/src/ent/generated/account_base.ts
examples/todo-sqlite/src/ent/generated/tag_base.ts
examples/todo-sqlite/src/ent/generated/todo_base.ts
examples/todo-sqlite/src/ent/generated/workspace_base.ts
examples/todo-sqlite/src/ent/tests/account.test.ts
examples/todo-sqlite/src/ent/tests/todo.test.ts
internal/codegen/config.go
internal/tscode/base.tmpl
ts/src/core/config.ts

read side of https://github.com/lolopinto/ent/pull/1597

rename withoutTransform load methods

---

python/auto_schema/auto_schema/compare.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/tests/conftest.py
python/auto_schema/tests/runner_test.py

related https://github.com/lolopinto/ent/issues/1615 for handling it better

error for when changing server_default to non-null and nullable to false

---

examples/simple/src/schema/schema.sql
examples/simple/src/schema/versions/63ec20382c27_2023720223223_ggsgsf.py
internal/db/db_schema.go
python/auto_schema/auto_schema/clearable_string_io.py
python/auto_schema/auto_schema/command.py
python/auto_schema/auto_schema/renderers.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/setup.py
python/auto_schema/tests/runner_test.py

related: https://github.com/lolopinto/ent/pull/838, https://github.com/lolopinto/ent/pull/1555

Missing custom sql in generated schema.sql

---

python/auto_schema/auto_schema/runner.py

follow-up to https://github.com/lolopinto/ent/pull/1619

fix include_rev

---

internal/db/db_schema.go
internal/graphql/generate_ts_code.go
internal/util/terminal_colors.go
tsent/cmd/root.go
tsent/cmd/squash.go

follow-up to https://github.com/lolopinto/ent/pull/1621
addresses https://github.com/lolopinto/ent/issues/1543

integrate squash all into CLI

---

ts/src/schema/struct_field.test.ts
ts/src/schema/struct_field.ts

fixes https://github.com/lolopinto/ent/issues/1632

fix issue when there's graphql/typescript mismatch with unique key validation

---

ts/src/core/base.ts
ts/src/core/clause.test.ts
ts/src/core/clause.ts
ts/src/core/db_clause.test.ts
ts/src/core/query_impl.ts

used in https://github.com/lolopinto/ent/pull/1635 and lifted out of that

aliases for Clause

---

examples/simple/src/ent/contact/actions/create_contact_action.ts
ts/package.json
ts/src/action/transaction.ts

reuse `EntBuilder` from `experimental_action` and add more templating
https://github.com/lolopinto/ent/issues/1645

change type of ActionAny in transaction

---

examples/simple/tsconfig.json
ts/src/action/action.ts
ts/src/action/executor.ts
ts/src/action/operations.ts
ts/src/action/orchestrator.test.ts
ts/src/action/orchestrator.ts
ts/src/action/orchestrator_edge.test.ts
ts/src/testutils/action/complex_schemas.ts

https://github.com/lolopinto/ent/issues/1645

change type for Operations and a bunch of related ish

---

examples/simple/src/graphql/generated/mutations/user_auth_jwt_type.ts
examples/simple/src/graphql/generated/mutations/user_auth_type.ts
examples/simple/src/graphql/generated/resolvers/comment_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/comment_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/contact_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/contact_email_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/contact_email_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/contact_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/contact_phone_number_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/contact_phone_number_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/event_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/event_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/holiday_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/holiday_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/hours_of_operation_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/hours_of_operation_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/user_connection_query_type.ts
examples/simple/src/graphql/generated/resolvers/user_list_deprecated_query_type.ts
examples/simple/src/graphql/generated/resolvers/viewer_query_type.ts
examples/simple/src/graphql/generated/schema.gql
examples/simple/src/graphql/mutations/auth.ts
examples/simple/src/graphql/mutations/auth_types.ts
examples/simple/src/graphql/resolvers/gql_viewer.ts
examples/simple/src/graphql/resolvers/viewer.ts
internal/graphql/custom_ts.go
internal/graphql/generate_ts_code.go
internal/graphql/ts_templates/field_config.tmpl

fixes https://github.com/lolopinto/ent/issues/1650

add missing decorations to custom graphql

---

.github/workflows/python_ci.yml

fixes https://github.com/lolopinto/ent/issues/1617

[auto_schema] pytest matrix

---

ts/package.json
ts/src/core/query/custom_query.ts
ts/src/graphql/graphql.ts
ts/src/scripts/custom_graphql.ts

fix a custom_graphql type

---

ts/src/core/base.ts
ts/src/core/context.ts
ts/src/core/db_clause.test.ts
ts/src/core/ent.ts
ts/src/core/query_impl.ts

fixes https://github.com/lolopinto/ent/issues/1661

support multiple joins

---

CHANGELOG.md
ts/package.json

was actually created in https://github.com/lolopinto/ent/pull/1680

@snowtop v0.1.19

---

CHANGELOG.md
ts/package.json

* https://github.com/lolopinto/ent/pull/1665
* https://github.com/lolopinto/ent/pull/1673
* https://github.com/lolopinto/ent/pull/1674
* https://github.com/lolopinto/ent/pull/1677

bump @snowtop/ent version for unreleased changes

---

examples/todo-sqlite/src/ent/generated/mixins/todo_container/actions/todo_container_builder.ts
internal/tscode/mixin_builder.tmpl

apparently, in TS strict mode, it complains

export interfaces and other types generated in mixins

---

release_image/main.go
ts/Dockerfile
ts/Dockerfile.tmpl

broken by https://github.com/lolopinto/ent/pull/1705
removed extra lines by mistake

fix docker build

---

examples/todo-sqlite/src/ent/generated/todo/actions/create_todo_action_base.ts
examples/todo-sqlite/src/ent/tests/tag.test.ts
examples/todo-sqlite/src/ent/todo/actions/create_todo_action.ts
examples/todo-sqlite/src/graphql/generated/mutations/todo/create_todo_type.ts
examples/todo-sqlite/src/graphql/generated/schema.gql
examples/todo-sqlite/src/graphql/generated/schema.ts
examples/todo-sqlite/src/schema/todo_schema.ts
internal/field/field.go
internal/schema/schema.go

fixes https://github.com/lolopinto/ent/issues/1706

fix optional non-nullable field in action not being optional in certain actions

---

examples/simple/src/ent/contact/actions/edit_contact_action.ts
examples/simple/src/ent/generated/contact/actions/edit_contact_action_base.ts
examples/simple/src/ent/generated/mixins/feedback/actions/feedback_builder.ts
examples/simple/src/ent/tests/contact.test.ts
examples/simple/src/graphql/generated/mutations/contact/contact_edit_type.ts
examples/simple/src/graphql/generated/schema.gql
examples/simple/src/graphql/generated/schema.ts
examples/simple/src/schema/contact_schema.ts
internal/action/action.go
internal/action/action_types.go
internal/action/interface.go
internal/field/field.go
internal/field/non_ent_field.go
internal/graphql/generate_ts_code.go
internal/schema/schema.go

fixes https://github.com/lolopinto/ent/issues/1706 again

fix #1706. take 2 but with edit actions

---

docker_CHANGELOG.md
examples/ent-rsvp/backend/src/ent/generated/event/actions/create_event_action_base.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity/actions/edit_event_activity_rsvp_status_action_base.ts
examples/ent-rsvp/backend/src/ent/tests/event_activity.test.ts
examples/ent-rsvp/backend/src/testutils/index.ts
internal/tscode/action_base.tmpl
ts/src/action/action.ts

wrong NodeType was being set in the codegen code 
addresses https://github.com/lolopinto/ent/issues/1718

fix EdgeGroup actions sets incorrect ent type in DB

---

docker_CHANGELOG.md
internal/field/compare_field.go

addresses https://github.com/lolopinto/ent/issues/1725

change error message when changing database type to be more descriptive

---

CHANGELOG.md
ts/CONTRIBUTING.md
ts/src/parse_schema/parse.ts
tsent/cmd/parse_schema_cmd.go
tsent/cmd/root.go

fixes https://github.com/lolopinto/ent/issues/1703

validate that we can't have multiple patterns with the same name

---

CHANGELOG.md
ts/package.json

for https://github.com/lolopinto/ent/pull/1745

new snowtop version

---

examples/ent-rsvp/backend/src/ent/generated/guest_base.ts
examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/simple/src/ent/generated/event/actions/event_builder.ts
examples/simple/src/ent/generated/loaders.ts
examples/simple/src/graphql/generated/schema.gql
examples/simple/src/schema/event_schema.ts
examples/todo-sqlite/src/graphql/generated/resolvers/custom_todos_query_type.ts
internal/edge/edge.go
internal/field/field.go

addresses some part of https://github.com/lolopinto/ent/issues/674
follow-up to https://github.com/lolopinto/ent/pull/1757

make it so that fooId UUID fieldEdge works

---

examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/simple/src/graphql/generated/schema.gql
examples/todo-sqlite/src/graphql/generated/schema.gql
internal/graphql/generate_ts_code.go

broken by https://github.com/lolopinto/ent/pull/1768
what seemed to need it was fixed by https://github.com/lolopinto/ent/pull/1780

fix generated date types

---

internal/graphql/custom_data.go

followup to https://github.com/lolopinto/ent/pull/1795

use getNodeNameFor

---

examples/ent-rsvp/backend/src/ent/event_activity/actions/event_activity_add_invite_action.ts
examples/ent-rsvp/backend/src/ent/generated/event_activity/actions/event_activity_add_invite_action_base.ts
examples/ent-rsvp/backend/src/ent/guest_group/actions/create_guest_group_action.ts
examples/ent-rsvp/backend/src/ent/tests/event_activity.test.ts
examples/ent-rsvp/backend/src/graphql/generated/mutations/event_activity/event_activity_add_invite_type.ts
examples/ent-rsvp/backend/src/graphql/generated/resolvers/event_activity_type.ts
examples/ent-rsvp/backend/src/graphql/generated/schema.gql
examples/ent-rsvp/backend/src/schema/event_activity_schema.ts
examples/ent-rsvp/backend/src/testutils/index.ts
internal/action/action.go
internal/action/compare_action_test.go
internal/graphql/generate_ts_code.go
internal/schema/input/parse_ts_edge_test.go
internal/tscode/action_base.tmpl

fixes https://github.com/lolopinto/ent/issues/1803

stop ignoring actionOnlyFields in edge actions

---

python/auto_schema/auto_schema/clause_text.py
python/auto_schema/auto_schema/command.py
python/auto_schema/auto_schema/compare.py
python/auto_schema/auto_schema/csv.py
python/auto_schema/auto_schema/diff.py
python/auto_schema/auto_schema/ops.py
python/auto_schema/auto_schema/ops_impl.py
python/auto_schema/auto_schema/renderers.py
python/auto_schema/auto_schema/runner.py
python/auto_schema/tests/command_test.py
python/auto_schema/tests/conftest.py
python/auto_schema/tests/runner_test.py
python/auto_schema/tests/testingutils.py

[auto_schema] cleanup

---

.github/workflows/codeql-analysis.yml

mostly reverting https://github.com/lolopinto/ent/pull/1791/files

fix codeql

---

CHANGELOG.md
ts/package.json

for https://github.com/lolopinto/ent/pull/1829

new snowtop

---

.github/workflows/node.js.yml
ts/src/core/db_postgres_parallel.test.ts

bandaid to hopefully get tests consistently passing

increase max_connections for node js postgres tests

---

release_image/main.go

for https://github.com/lolopinto/ent/pull/1848

docker v0.2.0-alpha.11

---

CHANGELOG.md
ts/package.json

snowtop 2.0

---

ts/src/schema/field.ts

As the title says.
Fixes #1860

Handle null/undefined date values

---

internal/edge/edge.go
internal/schema/input/input.go
internal/schema/schema.go
internal/schema/schema_input_test.go
internal/tscode/ent_query_base.tmpl
ts/src/schema/schema.ts

annoying to query and get results sorted by id. id sorting is useless. allows specifying a sort and using it

ability to customize default ordering for an indexed edge

---

ts/src/graphql/tests/file_upload.test.ts

fix flaky test
