- internal/graphql/custom_ts_test.go
- ts/src/graphql/graphql.test.ts
- ts/src/graphql/graphql.ts
- ts/src/graphql/graphql_custom.test.ts
- ts/src/graphql/graphql_field_helpers.ts
- ts/src/graphql/query/connection_type.ts
would need to change both TypeScript and Go to support this. so intead just throw an exception and move on.
Error thrown by Go: `Error: found a type Point which was not part of the schema`
fixes https://github.com/lolopinto/ent/issues/335
original relevant PRs: https://github.com/lolopinto/ent/pull/65 and https://github.com/lolopinto/ent/pull/241
> handle custom Scalar Types passed in

- internal/db/db_schema.go
- python/auto_schema/CONTRIBUTING.MD
- python/auto_schema/RELEASING.MD
- python/auto_schema/auto_schema/cli/__init__.py
- python/auto_schema/auto_schema/command.py
- python/auto_schema/auto_schema/runner.py
- python/auto_schema/setup.py
- tsent/cmd/alembic.go
- tsent/cmd/root.go
This adds support for more [alembic commands](https://alembic.sqlalchemy.org/en/latest/api/commands.html) to auto_schema.
The only ones left are `list_templates` (doesn't seem relevant) and `merge`: tracked at https://github.com/lolopinto/ent/issues/316
This also adds a blanket `tsent alembic` which can be used to run any alembic command instead of creating a top-level command for rarely used things. For example:
```shell
tsent alembic current
```
shows the current version
We still keep `upgrade` and `downgrade` as top level commands since they're used relatively often.
Also fixes `upgrade` to accept being passed a non 'heads' version
This also updates and publishes latest auto_schema version as 0.0.7
> Update auto schema

- internal/graphql/generate_ts_code.go
broken by https://github.com/lolopinto/ent/pull/342
in https://github.com/lolopinto/ent/pull/342, the schema.tmpl file was changed to be retrieved from `schema.ts` instead of creating a new schema. However, schema.ts was being generated after that which leads to an error for new projects.  
Also, it means that we'd need to run codegen multiple times to see the schema reflected in `schema.tmpl`. I kinda remember seeing this now.
> reorder graphql steps

- ts/packages/ent-graphql-tests/package.json
- ts/packages/ent-graphql-tests/src/index.ts
- ts/packages/ent-graphql-tests/src/test.ts
- ts/src/graphql/node_resolver.test.ts
- ts/src/testutils/ent-graphql-tests/index.ts
when querying for a field which was a scalar list e.g. list of strings, we were trying to expand that and query subfields which didn't exist.
> fix ent-graphql-tests when we're querying for scalar lists

- ts/src/scripts/custom_graphql.ts
- ts/src/scripts/read_schema.ts
was debugging and ran into this issue:
```shell
Creating ent-starter_app_run ... done
/bin/sh: 1: : not found
(node:9) UnhandledPromiseRejectionWarning: Error: /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:14)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:92:18)
at bindings (/app/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/app/node_modules/better-sqlite3/lib/database.js:9:24)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js …
```
> catch errors in the scripts

- internal/graphql/generate_ts_code.go
- internal/graphql/ts_templates/index.tmpl
@lolopinto/ent was hardcoded somewhere else
[skip ci]
more followups to https://github.com/lolopinto/ent/pull/377 and https://github.com/lolopinto/ent/pull/379
> one more snowtop fix

- internal/tscode/ent_query_base.tmpl
- ts/package.json
- ts/src/core/ent.ts
- ts/src/core/ent_custom_data.test.ts
- ts/src/core/loaders/assoc_count_loader.test.ts
- ts/src/core/loaders/assoc_count_loader.ts
- ts/src/core/loaders/assoc_edge_loader.ts
- ts/src/core/loaders/index.ts
- ts/src/core/loaders/index_loader.test.ts
- ts/src/core/loaders/index_loader.ts
- ts/src/core/loaders/query_loader.test.ts
- ts/src/core/loaders/query_loader.ts
- ts/src/core/loaders/raw_count_loader.test.ts
- ts/src/core/loaders/raw_count_loader.ts
- ts/src/core/logger.ts
- ts/src/core/query/assoc_query_sqlite.test.ts
- ts/src/core/query/complex_custom_query.test.ts
- ts/src/core/query/query.ts
- ts/src/core/query/shared_test.ts
- ts/src/graphql/graphql.ts
- ts/src/testutils/db/test_db.ts
- ts/src/testutils/fake_data/fake_contact.ts
- ts/src/testutils/fake_data/fake_event.ts
- ts/src/testutils/fake_data/fake_user.ts
- ts/src/testutils/fake_data/test_helpers.ts
- ts/src/testutils/fake_data/user_query.ts
- ts/src/testutils/mock_date.ts
make it so that we can use custom queries as entquery 
kind of a followup to https://github.com/lolopinto/ent/pull/390
now, defining custom query clause and you get entquery with pagination etc 
next, ability to add a decorator and have a graphql connection exposed so that it's as first class a citizen as the ones exposed by the framework based on the schema
This refactors IndexLoader into QueryLoader which is more flexible to support the base cases we previously supported e.g.
* indexed field (what we already support)
* indexed field and extraClause (new). an s
* just clause for super custom cases. this won't be grouped into the same query but will still work for entquery etc
> Custom queries ent query

- examples/ent-rsvp/backend/package-lock.json
- examples/ent-rsvp/backend/package.json
- ts/package.json
- ts/src/core/config.test.ts
- ts/src/core/config.ts
- ts/src/core/db.ts
been meaning to do this. needed if partial configuration is taken from different places e.g. env variables for db
> make loadConfig take a JavaScript object too.

- .github/workflows/go_ci.yml
- .github/workflows/new_docker_image.yml
- release_image/main.go
- ts/Dockerfile
- ts/Dockerfile.tmpl
- ts/RELEASING.MD
* use multi-stage builds and remove cruft we don't need
there's now 6 images per release:
* node 14 dev (has dependencies for codegen e.g. prettier, tsconfig-paths, typescript, /bin/zsh for better shell)
* node 14 slim (without the above, we still have tsent and auto_schema for database upgrades)
* node 15 dev
* node 15 slim
* node 16 dev
* node 16 slim
if tsent and auto_schema aren't needed, nodejs images from docker can be used directly
add caching to github action by outputting to registry 
libpq-dev needed for https://www.psycopg.org/docs/install.html
here's what sizes look like now:
```
% docker image ls | grep ghcr.io/lolopinto/ent  | grep -v "<none>"
ghcr.io/lolopinto/ent                                             0.0.20-nodejs-16-slim        a138f0ac48cf   About an hour ago …
```
> smaller docker images

- gent/cmd/codegen.go
- internal/code/codegen_plugin.go
- internal/codegen/codegen_processor.go
- internal/db/db_schema.go
- internal/graphql/custom_functions_test.go
- internal/graphql/custom_ts.go
- internal/graphql/custom_ts_test.go
- internal/graphql/ent_graphql_server_plugin.go
- internal/graphql/generate_ts_code.go
- internal/graphql/graphql_schema.go
- internal/graphql/graphql_schema_test.go
- internal/tscode/step.go
probably faster and more importantly, we find any errors before we start making changes
plus  rename codegen.CodegenProcessor to Processor
looks better. still not clear this is the correct name
and parallelize pre-processing 
builds on top of https://github.com/lolopinto/ent/pull/410
> move parsing custom graphql data into preprocess step.

- internal/codegen/codegen_processor.go
- internal/db/db_schema.go
- internal/file/writer.go
- internal/graphql/generate_ts_code.go
- internal/tscode/step.go
- tsent/cmd/codegen.go
- tsent/cmd/root.go
and when the debug flag isn't passed (default behavior), we only log high level information as to what's happening
now that https://github.com/lolopinto/ent/pull/410 exists, we need what's being logged to be high level information so that if there's a prompt, it's not drowned in the sea of files being chnaged
over time, this will need to be updated but works fine for now.
> add debug flag to log the files being changed

- docs/docs/advanced-topics/deploying.md
no longer needed once we moved to @snowtop/ent which is in npm instead of ghithub packages
> remove .npmrc part of deploying.md

- ts/package.json
- ts/src/scripts/custom_compiler.ts
now that we use
```ts
import type { RunResult, Database as SqliteDatabase } from "better-sqlite3";
``` 
in core/db.ts
"better-sqlite3" doesn't exist when compiling dependencies leading to an error. we shouldn't have an error here since undefined is valid
> update custom_compiler to always return something

- docs/docs/ent-schema/constraints.mdx
The exact copy was used in the unique constraint paragraph above and it was confusing initially to understand how these were different.
> Update language for primary key constraints

- ts/package.json
- ts/src/action/orchestrator.test.ts
- ts/src/action/orchestrator.ts
- ts/src/schema/schema.ts
* change `defaultValueOnCreate` to take builder and input so that it can be used to default to viewer or something else
* add `defaultToViewerOnCreate` for hte common use case which inspired these changes 
for https://github.com/lolopinto/ent/issues/435
> two changes to Field APIs

- internal/codegen/codegen_processor.go
- internal/codegen/prompts.go
- internal/db/db_schema.go
both paths are running the same code
https://github.com/lolopinto/ent/blob/main/python/auto_schema/auto_schema/runner.py#L185
https://github.com/lolopinto/ent/blob/main/python/auto_schema/auto_schema/runner.py#L258
so no reason to call this twice.
we just keep a flag in golang that we check and avoid the overhead a second time
way simpler than options presented at https://github.com/lolopinto/ent/issues/453
> when there's no db changes, no need to call into auto_schema a second time

- internal/codegen/codegen_processor.go
- internal/graphql/custom_ts.go
- internal/graphql/custom_ts_test.go
- internal/graphql/generate_ts_code.go
- internal/graphql/ts_templates/schema.tmpl
- internal/tscode/step.go
- tsent/cmd/codegen_test.go
this chain of changes is apparently cursed.
broken by https://github.com/lolopinto/ent/pull/454 
issue was the last value in the loop captured in the closure was the same for each iteration so we kept rewriting the same files instead of writing  other files. noticed when making another change and not seeing my changes reflected there.
more details: https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
adds graphql tests that were missing from https://github.com/lolopinto/ent/pull/449. another fix to https://github.com/lolopinto/ent/issues/446
> Fix codegen

- .github/workflows/go_ci.yml
- examples/simple/package-lock.json
- examples/simple/package.json
- ts/package-lock.json
- ts/package.json
- ts/src/core/db.ts
- ts/tsconfig.json
fixes https://github.com/lolopinto/ent/issues/463
[import type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) not working here leading to downstream issues. 
fix is to just skip that and have our own interfaces for now?
> don't use import type

- python/Pipfile
- python/Pipfile.lock
- python/auto_schema/CONTRIBUTING.MD
- python/auto_schema/RELEASING.MD
- python/auto_schema/setup.py
add python-dateutil dependency
release auto_schema version 0.0.10
was seeing this error:
```
Traceback (most recent call last):
File "/opt/venv/bin/auto_schema", line 8, in <module>
sys.exit(main())
File "/opt/venv/lib/python3.8/site-packages/auto_schema/cli/__init__.py", line 72, in main
r.run()
File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 187, in run
self._apply_changes(diff)
File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 202, in _apply_changes
raise err
File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 196, in _apply_changes
self.revision(diff)
File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 225, in revision
self.cmd.revision(message)
File …
```
> pin auto_schema to specific versions

- internal/schema/input/input.go
- ts/package.json
- ts/src/core/query/assoc_query.ts
- ts/src/core/query/shared_assoc_test.ts
- ts/src/graphql/graphql.ts
- ts/src/graphql/query/connection_type.ts
- ts/src/parse_schema/parse.ts
- ts/src/schema/base_schema.ts
- ts/src/schema/schema.ts
- ts/src/scripts/read_schema.ts
- ts/src/testutils/fake_data/const.ts
- ts/src/testutils/fake_data/fake_user.ts
- ts/src/testutils/fake_data/user_query.ts
TypeScript API to allow edges in Patterns.
Allows for reusable functionality e.g. feedback with likes and comments
This will be paired with corresponding change in golang
Included:
* refactors `src/scripts/read_schema.ts` into `src/parse_schema/parse.ts` which can be [independently tested](https://github.com/lolopinto/ent/issues/505)
* change `AssocEdgeQueryBase` to take a factory method which given the nodeType returns the correct load options which will be used to load the ent. Needed to support polymorphic edges where id2 can be different types
* **breaking change** by making `name` in Pattern required
* adds `edgeConstName` to `AssocEdge` and `InverseAssocEdge` so that the developer can specify what the generated edge should be called
* changes read_schema script to output patterns …
> TS: Add edges to Patterns

- ts/src/action/action.ts
- ts/src/action/executor.test.ts
- ts/src/action/orchestrator.ts
what we had was too restrictive and forced things that could return a list of changesets or void not to work
> improve type for TriggerReturn

- internal/schema/input/input.go
- ts/package.json
- ts/src/schema/field.ts
- ts/src/schema/string_field.test.ts
- ts/src/schema/uuid_field.test.ts
if we had a polymorphic field that's nullable, the derived `type` field wasn't leading to errors. this fixes that
fixes https://github.com/lolopinto/ent/issues/540
> nullable derived type when polymorphic field is null

- .github/workflows/go_ci.yml
- gent/cmd/upgrade.go
- internal/db/db_schema.go
- test_setup/main.go
- tsent/cmd/alembic.go
- tsent/cmd/downgrade.go
- tsent/cmd/root.go
- tsent/cmd/squash.go
- tsent/cmd/upgrade.go
uses https://github.com/lolopinto/ent/pull/549
* adds `merge_branches` flag to `upgrade` command
* uses `keep_schema_files` in `downgrade` command correctly
* adds new `squash` top level command
* adds new alembic `merge` "subcommand" so that `tsent alembic heads` can be run by developer and not depend on what happens at https://github.com/lolopinto/ent/pull/546
> changes to golang CLI for new auto_schema version

- examples/ent-rsvp/backend/package-lock.json
- examples/ent-rsvp/backend/package.json
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/todo-sqlite/package-lock.json
- examples/todo-sqlite/package.json
- ts/package.json
which is a known bad revision
use https://semver.npmjs.com/ to confirm that it skips it
https://github.com/lolopinto/ent/issues/582
update examples to 15.7.2 (latest) and confirm things work
> update graphql peer dependency to skip 15.4

- ts/src/core/privacy.ts
Requires a caller to specify the Ent type into the `AllowIfViewerIsRule`, so that Typescript can validate the string key passed in.
This isn't backwards compatible, so leaving up to you whether you want this in. It would just require going in and adding the generic to every use case.
VALID
`new AllowIfViewerIsRule<Ent>('id')`
TYPE ERROR
`new AllowIfViewerIsRule<Ent>('is')`
> Add generics to AllowIfViewerIsRule

- .github/workflows/go_ci.yml
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/graphql/resolvers/viewer.ts
- internal/graphql/generate_ts_code.go
- internal/tscode/step.go
- internal/util/script_file.go
- ts/package.json
- ts/src/imports/imports.test.ts
- ts/src/imports/index.ts
- ts/src/scripts/custom_graphql.ts
use [rg](https://github.com/BurntSushi/ripgrep) for searching to see if we have custom code before loading the code to parse it.
more info on rg: https://blog.burntsushi.net/ripgrep/
Also considered [ag](https://github.com/ggreer/the_silver_searcher).
this makes it so that if there's no custom code, we don't pay the penalty of loading all the code and it's faster to run codegen. when there's custom code, it's still slow enough that we have to solve a different way eventually e.g. something like tsc-watch but that's for later.
part of addressing https://github.com/lolopinto/ent/issues/595
> use rg to search for custom code 

- examples/simple/tsconfig.json
- gent/cmd/root.go
- go.mod
- go.sum
- internal/codegen/codegen_processor.go
- internal/codegen/config.go
- internal/file/options.go
- internal/file/template_file_writer.go
- internal/file/writer.go
- internal/file/yaml_file_writer.go
- internal/filehelper/parse.go
- internal/graphql/generate_ts_code.go
- ts/src/core/config.ts
right now, we overwrite files during codegen even if nothing has changed. we then have to run prettier on large swaths of code which is very slow on non-arm64 builds
this improves that by doing the following things: 
* when a file is to be written once, we skip generating everything if the file already exists on disk
* we use [esbuild](https://github.com/evanw/esbuild)'s API to compare the minified version of the new code with the minified version what exists on disk and skip writing if nothing's changed
* we keep track of changed TS files (if any) and pass that to prettier to only format the files which have changed
this leads to a noticeable performance improvement on non-arm64 builds (e.g. on an AWS devserver). we're doing even more I/O which isn't cheap so there's still lots of …
> improvements to writing files + prettier usage

- .github/workflows/node.js.yml
- release_image/main.go
- ts/package.json
based on https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382
https://github.com/nodejs/release
updated current to 17
fixes https://github.com/lolopinto/ent/issues/583
updates engines https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines. it was somehow set to 16.1 even though we support 14+
> node 17 support

- tsent/cmd/root.go
colorify "Error:" so that it's clearer when there's one
> add ansi-color to Error:

- examples/ent-rsvp/backend/package-lock.json
- examples/ent-rsvp/backend/package.json
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/ent/comment/actions/generated/comment_builder.ts
- examples/simple/src/ent/comment/actions/generated/create_comment_action_base.ts
- examples/simple/src/ent/generated/comment_base.ts
- examples/simple/src/ent/tests/user.test.ts
- examples/simple/src/graphql/generated/schema.gql
- examples/simple/src/graphql/resolvers/generated/comment_type.ts
- examples/simple/src/schema/comment.ts
- examples/todo-sqlite/package-lock.json
- examples/todo-sqlite/package.json
- internal/edge/edge.go
- internal/field/field_type.go
- ts/package.json
- ts/src/action/action.ts
- ts/src/action/orchestrator.ts
- ts/src/schema/base_schema.ts
- ts/src/schema/field.ts
- ts/src/schema/schema.ts
- ts/src/schema/uuid_field.test.ts
https://github.com/lolopinto/ent/issues/476
```ts title='src/schema/comment.ts'
export default class Comment extends BaseEntSchema implements Schema {
fields: Field[] = [
// don't want a foreign key but want to type the User
UUIDType({ name: "AuthorID", fieldEdge: { schema: "User" } }),
];
}
```
generates 
```ts title='src/ent/generated/comment_base.ts'
class CommentBase {
... 
async loadAuthor(): Promise<User | null> {
return loadEnt(this.viewer, this.authorID, User.loaderOptions());
}
loadAuthorX(): Promise<User> {
return loadEntX(this.viewer, this.authorID, User.loaderOptions());
}
}
```
and to enforce the type, update to 
```ts title='src/schema/comment.ts'
export default class Comment extends BaseEntSchema implements Schema {
fields: Field[] = [
// don't want a foreign key but want …
```
> support fieldEdge that's not a foreignKey/inverseEdge and optionally validates that id is of type Foo

- examples/ent-rsvp/backend/package-lock.json
- examples/ent-rsvp/backend/package.json
- examples/ent-rsvp/backend/src/ent/address/actions/generated/address_builder.ts
- examples/ent-rsvp/backend/src/ent/auth_code/actions/generated/auth_code_builder.ts
- examples/ent-rsvp/backend/src/ent/event/actions/generated/event_builder.ts
- examples/ent-rsvp/backend/src/ent/event_activity/actions/generated/event_activity_builder.ts
- examples/ent-rsvp/backend/src/ent/guest/actions/generated/guest_builder.ts
- examples/ent-rsvp/backend/src/ent/guest_data/actions/generated/guest_data_builder.ts
- examples/ent-rsvp/backend/src/ent/guest_group/actions/generated/guest_group_builder.ts
- examples/ent-rsvp/backend/src/ent/user/actions/generated/user_builder.ts
- examples/ent-rsvp/backend/src/graphql/mutations/generated/address/address_edit_type.ts
- examples/ent-rsvp/backend/src/graphql/mutations/generated/event_activity/event_activity_edit_type.ts
- examples/ent-rsvp/backend/src/schema/event.ts
- examples/ent-rsvp/backend/src/schema/event_activity.ts
- examples/ent-rsvp/backend/src/schema/guest_group.ts
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/schema/contact.ts
- internal/enttype/type.go
- internal/field/field_type.go
- internal/graphql/graphql_fields_test.go
- internal/schema/input/input.go
- internal/schema/schema.go
- ts/package.json
- ts/src/schema/schema.ts
when an action's input is embedded in another action like
```
actions: Action[] = [
{
operation: ActionOperation.Create,
excludedFields: ["creatorID"],
actionOnlyFields: [
{
name: "activities",
list: true,
nullable: true,
type: "Object",
actionName: "CreateEventActivityAction",
},
],
},
```
see https://github.com/lolopinto/ent/blob/main/examples/ent-rsvp/backend/src/schema/event.ts#L22-L35
the logic of which fields to embed was removing all id fields, it worked for all the examples we had but wouldn't work if we had an object with lots of ids. this fixes that to just depend on the developer to understand the embedded contexts and exclude fields as needed
fixes https://github.com/lolopinto/ent/issues/677
> change embedded fields in action logic

- release_image/main.go
pointing to https://github.com/lolopinto/ent/releases/tag/v0.0.35 and https://github.com/lolopinto/ent/releases/tag/v0.0.36
> new (old) release

- .github/testdata/schema1.json
- .github/testdata/schema2.json
- .github/workflows/e2e.yml
- internal/action/interface.go
- internal/schema/input/input.go
- internal/schema/input/parse_ts_custom_field_test.go
- internal/tscode/action_base.tmpl
- ts/package.json
- ts/src/parse_schema/parse.ts
fixes https://github.com/lolopinto/ent/issues/694
* ParseSchema() in input.go was changed in https://github.com/lolopinto/ent/pull/506 to support multiple ways to parse the schema because of a breaking change. that ended up masking issues if there was an error json marshalling. considering that was a while ago, simplify by no longer supporting the old way
* when nullable: false is passed, the following error is shown
```
json: cannot unmarshal bool into Go struct field Action.schemas.actions.actionOnlyFields of type input.NullableItem
```
this is because JS version of the code supports multiple types but go doesn't. update the JS schema parsing to handle when nullable: false is passed. also fix a potential other scenario this could happen with polymorphic: false
* the way imports work in …
> multi-issue fix for #694

- .github/workflows/e2e.yml
- internal/action/action.go
- internal/action/action_test.go
- internal/action/interface.go
- internal/field/field.go
- internal/field/non_ent_field.go
- internal/graphql/custom_functions_test.go
we had two NonEntField type. one in internal/action and one in internal/field
the more fully fleshed out one in action.
this consolidates both in internal/field to make it easier to reason about and use
> [cleanup] NonEntField consolidation

- internal/codegen/codegen_processor.go
- internal/codegen/prompts.go
- internal/prompt/prompt.go
- tsent/cmd/delete_schema.go
- tsent/cmd/print_schema.go
- tsent/cmd/root.go
fixes https://github.com/lolopinto/ent/issues/670
used as follows:
`tsent delete_schema Holiday`
previously, deleting a schema was annoying and error-prone. Now, it should be better.
> delete_schema command

- internal/tscode/step.go
go and its scope issues
i've seen an extra dangling file a few times because of this
> fix broken enum file generation

- examples/simple/package-lock.json
- examples/simple/package.json
- ts/package.json
- ts/src/parse_schema/parse.ts
- ts/src/schema/schema.ts
will be removed before merging back into main
doing this so that transform_schema can be called once when migrating from main -> v0.1 instead of having to be done multiple times. also simplifies the transform_schema code...
> compatibility mode for making changes in old schema.

- ts/package.json
- ts/src/core/loaders/assoc_edge_loader.ts
this was exposed by changing from `tsc` to `@swc/jest` and some tests (in a client) started failing
```
> const AssocEdge = require('./core/ent').AssocEdge
undefined
> const fn = ()=>AssocEdge
undefined
> AssocEdge.prototype.constructor.name
'AssocEdge'
> fn.prototype?.constructor.name
undefined
>
```
not really sure what's happening here but it seems like with @swc/jest, the prototype of an anonymous function is defined.
current "fix" is to chehck if the length of the name is > 0
code here was originally introduced in https://github.com/lolopinto/ent/pull/285
> fix weird bug with assoc_edge_loader

- examples/todo-sqlite/src/graphql/mutations/generated/tag/tag_create_type.ts
- examples/todo-sqlite/src/graphql/mutations/generated/todo/todo_create_type.ts
- internal/enttype/type.go
- internal/graphql/generate_ts_code.go
`mustDecodeIDFromGQLID` and `mustDecodeNullableIDFromGQLID` could be found as dangling imports without being used
> Fix dangling import

- examples/simple/package-lock.json
- examples/simple/package.json
- ts/src/action/executor.test.ts
- ts/src/action/orchestrator.test.ts
- ts/src/core/query/complex_custom_query.test.ts
- ts/src/graphql/node_resolver.test.ts
- ts/src/parse_schema/parse.test.ts
- ts/src/parse_schema/parse.ts
- ts/src/schema/base_schema.ts
- ts/src/schema/index.ts
- ts/src/schema/postgres_schema_live.test.ts
- ts/src/schema/uuid_field.test.ts
- ts/src/scripts/transform_schema.ts
- ts/src/testutils/builder.ts
- ts/src/testutils/db/test_db_helpers.test.ts
- ts/src/testutils/fake_data/fake_contact.ts
- ts/src/testutils/fake_data/fake_event.ts
- ts/src/testutils/fake_data/fake_user.ts
- ts/src/testutils/fake_data/test_helpers.ts
addresses https://github.com/lolopinto/ent/issues/585
changes the API from 
```ts
export default class Holiday extends BaseEntSchemaWithTZ {
constructor() {
super();
this.addPatterns(new DayOfWeek());
}
fields: Field[] = [StringType({ name: "label" }), DateType({ name: "date" })];
actions = [
{
operation: ActionOperation.Create,
},
];
}
```
to 
```ts
const Holiday = new EntSchemaWithTZ({
patterns: [new DayOfWeek()],
fields: { label: StringType(), date: DateType() },
actions: [
{
operation: ActionOperation.Create,
},
],
});
export default Holiday;
```
new API is easier to use, less likely to make mistakes and don't have to deal with types since that's just passed in the constructor.  using patterns is the cleanest change so far
builds on top of the work done in …
> New Schema API

- gent/cmd/upgrade.go
- internal/db/db_schema.go
- python/auto_schema/auto_schema/cli/__init__.py
- python/auto_schema/auto_schema/command.py
- python/auto_schema/auto_schema/runner.py
- python/auto_schema/tests/command_test.py
- test_setup/main.go
- tsent/cmd/root.go
- tsent/cmd/upgrade.go
kill merge revisions
fixes https://github.com/lolopinto/ent/issues/620
when there are multiple branches and we want to create a new revision/change, instead of using a merge revision like we did in https://github.com/lolopinto/ent/pull/546, we should use multiple down branches.
this makes it easier to keep track of what's going on. if one is trying to switch between branches and trying to keep track of changes between branches and has to count the merge revision, it becomes too difficult and annoying
> [auto_schema]: No merge revs

- python/auto_schema/auto_schema/cli/__init__.py
- python/auto_schema/auto_schema/command.py
- python/auto_schema/auto_schema/runner.py
- python/auto_schema/setup.py
- python/auto_schema/tests/command_test.py
- tsent/cmd/alembic.go
- tsent/cmd/root.go
exposes verbose flag
exposes rev_range flag
adds a last flag which creates a rev_range to pass to the history command
addresses one of the gripes in https://github.com/lolopinto/ent/issues/642
> [auto_schema] provide more alembic history options

- internal/schema/node_data.go
- internal/tscode/action_base.tmpl
- internal/tscode/builder.tmpl
- internal/tscode/step.go
- internal/tscode/write_action.go
if you have an action that has an action only field which references a foreignKey or anything that generates a fieldEdge, we eventually have an error because we've not "reserved" that object
because field.TsBuilderImports returns strings instead of the full import type, we were trying to reference a field that doesn't exist
correct fix is to change TsBuilderImports from strings to ImportType so we don't need this hack with schema but that's a more involved fix
for now, we're just referencing all nodes in the schema to work around it
Test Plan: works on following schema:
```ts
// cat horse.ts horse_info.ts horse_pedigree_info.ts user.ts 
import { ActionOperation } from "@snowtop/ent";
import { Action, BaseEntSchema, Field, StringType } from "@snowtop/ent";
export default class Horse …
```
> fix referencing nested object in action

- internal/enttype/json_test.go
- internal/enttype/type.go
- internal/schema/input/input.go
- internal/schema/input/parse_ts_field_test.go
- internal/schema/node_data.go
more in the technical debt cleanup
uses json marshalling tricks to make it work
was added by https://github.com/lolopinto/ent/pull/511
also fixes https://github.com/lolopinto/ent/issues/703
> kill enttype.InputImportType

- internal/schema/node_data.go
- internal/tscode/action_base.tmpl
- internal/tscode/builder.tmpl
- internal/tscode/step.go
- internal/tscode/write_action.go
This reverts commit b52ab41bbbd94a322601a110baeffa2aacdebeac.
https://github.com/lolopinto/ent/pull/774 and its predecessors https://github.com/lolopinto/ent/pull/772, https://github.com/lolopinto/ent/pull/773 mean we can revert this change
> Revert "fix referencing nested object in action (#770)"

- internal/codegen/codegen_processor.go
- internal/codegen/config.go
back to src/ent and src/graphql blobs and check if the path exists
was original plan in https://github.com/lolopinto/ent/pull/794 but changed. in large codebases, lots of other files and not worth doing them here
> [cli] followup to https://github.com/lolopinto/ent/pull/794

- .github/workflows/e2e.yml
- .github/workflows/go_ci.yml
- examples/simple/src/ent/contact.ts
- examples/simple/src/ent/user.ts
- internal/schema/input/parse_ts.go
latest version of `ts-node` supports `--swc` flag to use that to transpile ts instead of default path.
there's still issues with using `swc` everywhere (see https://github.com/lolopinto/ent/issues/792) so only doing this while parsing the schema but it helps with speeding things up 
addresses https://github.com/lolopinto/ent/issues/595
> use swc for parse schema

- internal/graphql/generate_ts_code.go
found via looking at https://github.com/BurntSushi/ripgrep/issues/1159 that exit code 1 means no results
> check for exit code 1 with rg

- internal/action/compare_action.go
- internal/schema/compare_schema_test.go
it affects what files are added, deleted etc
also adds a test for edges
> if the name of a mutation is changed, we should handle it in graphql code generation

- examples/todo-sqlite/ent.yml
- internal/build_info/build_info.go
- internal/codegen/codegen_processor.go
- internal/codegen/codegenapi/api.go
- internal/codegen/config.go
- internal/graphql/generate_ts_code.go
- internal/tscode/step.go
- ts/src/core/config.ts
if ent.yml is changed which can cause a file to be deleted (e.g. graphql mutation name change), we want to delete that file
important if changing from noun_verb to verb_noun or vice versa for mutations
related: https://github.com/lolopinto/ent/pull/816 and https://github.com/lolopinto/ent/pull/819
> account for ent.yml changes which may cause schema changes which change files

- ts/src/graphql/node_resolver.ts
fixes https://github.com/lolopinto/ent/issues/824
not needed for clients which implement this interface and simplifies the API
needed for EntNodeResolver but that's fine
> remove NodeResolver.encode

- python/Pipfile
- python/Pipfile.lock
- python/auto_schema/auto_schema/change_type.py
- python/auto_schema/auto_schema/compare.py
- python/auto_schema/auto_schema/diff.py
- python/auto_schema/auto_schema/ops.py
- python/auto_schema/auto_schema/ops_impl.py
- python/auto_schema/auto_schema/renderers.py
- python/auto_schema/auto_schema/runner.py
- python/auto_schema/auto_schema/schema_item.py
- python/auto_schema/auto_schema/script.py.mako
- python/auto_schema/tests/conftest.py
- python/auto_schema/tests/runner_test.py
- python/auto_schema/tests/testingutils.py
addresses https://github.com/lolopinto/ent/issues/466
alembic autogenerate doesn't support full text search. we want to support this an option in ent and make it possible to configure access
currently only supports in postgres
docs: https://www.postgresql.org/docs/current/textsearch.html
https://www.postgresql.org/docs/current/textsearch-intro.html
https://www.postgresql.org/docs/current/textsearch-tables.html
also relevant reads https://blog.crunchydata.com/blog/postgres-full-text-search-a-search-engine-in-a-database, http://rachbelaid.com/postgres-full-text-search-is-good-enough/ for how it may want to be used
still need support in schema and help querying
high level things here:
* support adding index, removing index once in schema
* support index on stored generated column
* support …
> [auto_schema] support for full text index

- examples/simple/src/schema/schema.sql
- python/auto_schema/auto_schema/runner.py
by using name instead of _creation_order which is currently what the logic does. this is so that running codegen multiple times with no schema changes ends with the same file
> auto_schema: sort constraints in schema.sql consistently

- python/auto_schema/auto_schema/cli/__init__.py
- python/auto_schema/setup.py
followup to https://github.com/lolopinto/ent/pull/853
move warnings inside `main()` instead of if branch since that's not going to be called when being called from executable
> auto_schema. move warnings into main()

- .github/workflows/node.js.yml
- ts/src/index.ts
to support 14, 16, 17, 18
will drop 17 later
https://nodejs.org/en/blog/announcements/v18-release-announce/
nodejs release cycle always confuses https://nodejs.org/en/about/releases/
will update docker images later when new build is coming out
> nodejs 18: update test suites

- internal/field/field_type.go
seems weird. not used by any of the examples code and simplifies future changes
was originally added a while back in https://github.com/lolopinto/ent/pull/47 and doesn't seem relevant anymore
> kill EvolvedIDField check in Field.TsType

- examples/ent-rsvp/backend/src/ent/generated/address_base.ts
- examples/ent-rsvp/backend/src/ent/generated/auth_code_base.ts
- examples/ent-rsvp/backend/src/ent/generated/event_activity_base.ts
- examples/ent-rsvp/backend/src/ent/generated/event_base.ts
- examples/ent-rsvp/backend/src/ent/generated/guest_base.ts
- examples/ent-rsvp/backend/src/ent/generated/guest_data_base.ts
- examples/ent-rsvp/backend/src/ent/generated/guest_group_base.ts
- examples/ent-rsvp/backend/src/ent/generated/user_base.ts
- examples/simple/src/ent/generated/address_base.ts
- examples/simple/src/ent/generated/auth_code_base.ts
- examples/simple/src/ent/generated/comment_base.ts
- examples/simple/src/ent/generated/contact_base.ts
- examples/simple/src/ent/generated/contact_email_base.ts
- examples/simple/src/ent/generated/contact_phone_number_base.ts
- examples/simple/src/ent/generated/event_base.ts
- examples/simple/src/ent/generated/holiday_base.ts
- examples/simple/src/ent/generated/hours_of_operation_base.ts
- examples/simple/src/ent/generated/user_base.ts
- examples/todo-sqlite/src/ent/generated/account_base.ts
- examples/todo-sqlite/src/ent/generated/tag_base.ts
- examples/todo-sqlite/src/ent/generated/todo_base.ts
- internal/tscode/base.tmpl
fixes https://github.com/lolopinto/ent/issues/887
had a different version that typed everything (including the ent APIs) but it became too complicated so simplified to only type the public APIs
> type Foo.loadRawData

- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/ent/contact/actions/create_contact_action.ts
- examples/simple/src/ent/tests/contact.test.ts
- ts/package.json
- ts/src/action/orchestrator.test.ts
- ts/src/action/orchestrator.ts
- ts/src/testutils/builder.ts
as seen in `create_contact_action`, it makes the resulting ent code much easier to read.
doesn't work for autoincrement ids
also fixed a bug where `getDefaultValueOnCreate` may get called multiple times and so may have one id at the start and another when it's time to write
fixes https://github.com/lolopinto/ent/issues/605 and https://github.com/lolopinto/ent/issues/574
> provide a way to resolve id fields for default values

- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/ent/generated/address/actions/address_builder.ts
- examples/simple/src/ent/generated/auth_code/actions/auth_code_builder.ts
- examples/simple/src/ent/generated/comment/actions/comment_builder.ts
- examples/simple/src/ent/generated/contact/actions/contact_builder.ts
- examples/simple/src/ent/generated/contact_email/actions/contact_email_builder.ts
- examples/simple/src/ent/generated/contact_phone_number/actions/contact_phone_number_builder.ts
- examples/simple/src/ent/generated/event/actions/event_builder.ts
- examples/simple/src/ent/generated/event_base.ts
- examples/simple/src/ent/generated/holiday/actions/holiday_builder.ts
- examples/simple/src/ent/generated/hours_of_operation/actions/hours_of_operation_builder.ts
- examples/simple/src/ent/generated/loaders.ts
- examples/simple/src/ent/generated/user/actions/user_builder.ts
- examples/simple/src/ent/generated/user_base.ts
- internal/tscode/base.tmpl
- internal/tscode/builder.tmpl
- internal/tscode/loaders.tmpl
- ts/package.json
- ts/src/action/orchestrator.ts
- ts/src/core/ent_complex.test.ts
- ts/src/schema/schema.ts
- ts/src/testutils/builder.ts
fixes https://github.com/lolopinto/ent/issues/510
```go
import (
"fmt"
"github.com/iancoleman/strcase"
)
func main() {
fmt.Println(strcase.ToSnake("prefs2"))
}
// prefs_2 printed
```
```node
% node
Welcome to Node.js v17.0.1.
Type ".help" for more information.
> const s = require('snake-case')
undefined
> s.snakeCase('prefs2')
'prefs2'
> 
```
this difference in implementation leads to bugs when we run into one of these cases where the generated db col and what the JS thinks it is differ
now, we don't assume
> fix differences btw languages which causes weird issues

- internal/schema/node_data.go
- tsent/cmd/migrate_v0.1.go
if reparsing schema when we have schema which includes other codes, it leads to issues since paths may be broken
[skip ci]
> fix parsing schema in some situations

- internal/schema/schema.go
the way the code is written assumes that it's part of a structtype. i don't think worth rewriting everything yet to support that so just display an error for now
part of followup https://github.com/lolopinto/ent/issues/921
> error for top level union fields

- ts/package.json
- ts/src/tsc/transform_schema.ts
have transform_schema throw if it encounters files it can't change instead of failing silently
plus handle format that wasn't previously handled:
```ts
FooType({
name: 'name',
maxLen: 150,
}).formatter(formatter),
```
was previously failing. no longer failing
> transform_schema updates

- ts/package.json
- ts/src/action/action.test.ts
- ts/src/action/executor.test.ts
- ts/src/action/orchestrator.test.ts
- ts/src/core/config.test.ts
- ts/src/core/context.ts
- ts/src/core/ent.ts
- ts/src/core/ent_custom_data.test.ts
- ts/src/core/ent_data.test.ts
- ts/src/core/ent_logs.test.ts
- ts/src/core/loaders/assoc_count_loader.test.ts
- ts/src/core/loaders/assoc_edge_loader.test.ts
- ts/src/core/loaders/index_loader.test.ts
- ts/src/core/loaders/loader.ts
- ts/src/core/loaders/object_loader.test.ts
- ts/src/core/loaders/query_loader.test.ts
- ts/src/core/loaders/raw_count_loader.test.ts
- ts/src/core/logger.ts
- ts/src/core/query/complex_custom_query.test.ts
'query' is too noisy and makes it difficult to figure out what's happening.
> break query in log-levels into query and cache

- examples/todo-sqlite/src/ent/generated/tag_base.ts
- examples/todo-sqlite/src/graphql/generated/resolvers/tag_type.ts
- examples/todo-sqlite/src/graphql/generated/schema.gql
- examples/todo-sqlite/src/graphql/tests/tag.test.ts
- internal/edge/edge.go
- internal/edge/edge_test.go
- internal/field/fields_test.go
- internal/schema/schema.go
saw a scenario where I was getting an error
```
Cannot return null for non-nullable field Foo.bar
```
looked at the type and saw it was wrong.
also fixed an issue with Tag field `relatedTagIds` not having an edge generated for it 
more of https://github.com/lolopinto/ent/issues/644
https://github.com/lolopinto/ent/issues/674
> fix generated graphql type for nullable edge

- internal/graphql/generate_ts_code.go
- tsent/cmd/root.go
custom graphql disappears with no noticeable error and that's confusing
> flag missing rg (if running locally)

- internal/action/action_test.go
- internal/field/field_type.go
- internal/field/new_field_api.go
- internal/schema/input/compare.go
- internal/schema/input/input.go
- internal/schema/input/parse_ts_field_test.go
- internal/schema/input/parse_ts_test.go
- ts/package.json
- ts/src/parse_schema/parse.ts
- ts/src/schema/schema.ts
- tsent/cmd/generateschema/generate.go
- tsent/cmd/generateschema/generate_test.go
ent API and graphql accessor still unchanged
> ability to expose a private field to action.

- ts/src/core/db.ts
was harcoded to boolean which was preventing ssl and other complicated options
> fix Database.ssl type

- ts/src/core/clause.test.ts
- ts/src/core/clause.ts
- ts/src/core/db_clause.test.ts
there seems to be a performance benefit of using a values list instead of in() for large queries 
https://postgres.cz/wiki/PostgreSQL_SQL_Tricks_I#Predicate_IN_optimalization
i tried with a few queries when querying 100+ ids and timed the performance and there was a noticeable difference in some of them especially with large ids
variants i tried
* big in
```sql
select {cols} from {tbl} where id in ($1...$100) and foo = $101
```
* inner join
```sql
select {cols} from {tbl} inner join (values($1)...($100) ) v(hello) on (tbl::uuid = hello::uuid) and foo = $101
```
* values with cast on col
```sql
select {cols} from tbl where id::text  in (values($1)...($100)) and foo = $101
```
* values with cast on values 1st item
```sql
select {cols} from tbl where id in (values($1::uuid)...($100)) and foo …
```
>  In clause changes

- ts/src/core/ent_custom_data.test.ts
want to kill QueryRecorder and this is too important not to be hitting postgres
> change this test to use live postgres db instead of QueryRecorder

- internal/action/action_test.go
- internal/field/fields_test.go
- internal/graphql/custom_ts_test.go
- internal/graphql/graphql_fields_test.go
- internal/schema/schema_constraints_test.go
- internal/schema/schema_edge_test.go
- internal/schema/schema_test.go
- internal/schema/testhelper/test_helper.go
not to include base.TypeScript. only current supported lang and this code is always TS anyways
so if we eventually add separate language, it should be different API
> cleanup testhelper files 

- examples/ent-rsvp/backend/src/ent/generated/loadAny.ts
- examples/ent-rsvp/backend/src/ent/internal.ts
- examples/simple/src/ent/generated/loadAny.ts
- examples/simple/src/ent/internal.ts
- examples/todo-sqlite/src/ent/generated/loadAny.ts
- examples/todo-sqlite/src/ent/internal.ts
- internal/tscode/loadAny.tmpl
- internal/tscode/step.go
i think i initially did this intentionally but loadAny includes `src/ent` anyways so doesn't seem like there's much of a reason anyways
fixes https://github.com/lolopinto/ent/issues/1007
> include loadAny in src/ent includes

- ts/src/action/action.test.ts
- ts/src/action/orchestrator.ts
- ts/src/core/ent.test.ts
- ts/src/core/ent.ts
- ts/src/core/loaders/assoc_count_loader.ts
- ts/src/testutils/db/temp_db.ts
noticed it was still fetching all edges (limit to 1000) instead of just fetching row for `id1-edge_type-id2`
eventually, we could have some smart logic to use the most recent edges if we have caching, caching is cheap and edge count below a number but we're not there yet so better to aim for accuracy here
also did some optimization to do only one query for `getEdgeTypeInGroup` when the edges are stored in the same table (default case)
> loadEdgeForID2 cleanup

- internal/graphql/custom_data.go
- internal/graphql/custom_data_test.go
when comparing `CustomField` to see what has changed, we load data from `.ent/custom_schema_data.json` and end up double adding args. this checks for that and handles that
> fix connection args being added twice to unmarshaled and remarshaled CustomField

- internal/codegen/prompts.go
kinda followup to https://github.com/lolopinto/ent/pull/1232
even if we have a random bug like https://github.com/lolopinto/ent/pull/1232, should be smart about what happens
> if we somehow only have graphql-only changes, flag as no db changes

- .github/workflows/e2e.yml
- .github/workflows/python_ci.yml
- python/Pipfile
- python/Pipfile.lock
- python/auto_schema/setup.py
main reason is supposedly faster python 3.11 but upgrade most things too
> bump auto_schema

- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/ent/generated/loaders.ts
- examples/simple/src/ent/generated/user/actions/edit_user_all_fields_action_base.ts
- examples/simple/src/ent/generated/user/actions/user_builder.ts
- examples/simple/src/ent/generated/user_base.ts
- examples/simple/src/graphql/generated/resolvers/user_type.ts
- examples/simple/src/graphql/generated/schema.gql
- examples/simple/src/schema/user_schema.ts
- internal/action/action.go
- internal/db/db_schema.go
- internal/field/field.go
- internal/field/field_info.go
- internal/field/field_test.go
- internal/field/fields_test.go
- internal/graphql/generate_ts_code.go
- internal/schema/input/input.go
- internal/schema/node_data.go
- internal/schema/pattern_info.go
- internal/schema/schema.go
- internal/schema/schema_overrides_test.go
- internal/tscode/base.tmpl
- internal/tscode/loaders.tmpl
- internal/tscode/mixin.tmpl
- ts/package.json
- ts/src/schema/schema.ts
add dbOnly fields for fields that we want to still keep in the db but don't want in ent and graphql
allows fields to be dropped from the API but still keep in the db (hopefully for a little while before being dropped)
> Db only fields

- ts/packages/ent-graphql-tests/src/index.ts
- ts/src/action/executor.ts
- ts/src/core/context.ts
- ts/src/core/db.test.ts
- ts/src/core/ent_custom_data.test.ts
- ts/src/core/ent_data.test.ts
- ts/src/core/loaders/object_loader.test.ts
- ts/src/core/loaders/raw_count_loader.test.ts
- ts/src/core/loaders/raw_count_loader.ts
- ts/src/core/query/assoc_query_global.test.ts
- ts/src/core/query/shared_assoc_test.ts
- ts/src/core/query/shared_test.ts
- ts/src/graphql/graphql.test.ts
- ts/src/graphql/query/shared_assoc_test.ts
- ts/src/imports/dataz/example1/_viewer.ts
- ts/src/schema/field.ts
- ts/src/schema/schema_json.test.ts
- ts/src/schema/struct_field.test.ts
- ts/src/schema/struct_field.ts
- ts/src/testutils/db/value.test.ts
- ts/src/testutils/db/value.ts
- ts/src/testutils/ent-graphql-tests/index.ts
- ts/src/testutils/fake_data/events_query.ts
- ts/src/testutils/fake_data/fake_tag.ts
- ts/src/testutils/write.ts
left places that are using decorators and not explicitly referenced (used in tests)
> [cleanup] fix most things noUnusedLocals complains about

- ts/src/scripts/custom_graphql.ts
followup to https://github.com/lolopinto/ent/pull/1307
need to widen path because it was hiding things that it shouldn't
@gqlField is allowed and exists in EventActivityToAttendingEdge in `ent-rsvp/backend` example
> broaden custom objects paths

- python/auto_schema/tests/runner_test.py
- python/auto_schema/tests/testingutils.py
ran into weird issue with a second change added for server_default field which was apparently fixed with changes done in https://github.com/lolopinto/ent/pull/1329 when i was adding test for that
> [auto_schema] add test for new uuid field with server_default when field is added

- ts/package.json
- ts/src/action/orchestrator.test.ts
- ts/src/action/orchestrator.ts
2 things here
* officially support `defaultValueOnCreate` as async function
* format fields passed to ent constructor in unsafe ent creation for privacy policies. the generated ent have convertFoo methods which convert back from db and without formatting we eventually end up with weird behavior
> defaultValueOnCreate struct fixes

- ts/src/action/orchestrator.ts
followup to https://github.com/lolopinto/ent/pull/1370
call `valid` if possible
`ent-phonenumber` is weird and doesn't format if it can't and previously, have assumed that `valid` is called before `format`
> call valid in Orchestrator.getEntForPrivacyPolicyImpl

- ts/package.json
- ts/src/action/orchestrator.test.ts
- ts/src/action/orchestrator.ts
- ts/src/schema/base_schema.ts
- ts/src/schema/schema.ts
followup to https://github.com/lolopinto/ent/pull/671
allow fields with `defaultValueOnEdit` to be updated and have `updateInput` called so that if we call `getInput` in triggers/observers, we see the input
added a flag to schema.ts `onlyUpdateIfOtherFieldsBeingSet_BETA` so that the default `updatedAt` field behavior doesn't change
> defaultValueOnEdit change behavior

- examples/simple/src/graphql/generated/resolvers/viewer_query_type.ts
- examples/simple/src/graphql/resolvers/gql_viewer.ts
- examples/simple/src/graphql/resolvers/viewer.ts
```ts
decorator()
export class Foo {}
```
seems to lead to issues in TypeScript
googling points to https://github.com/microsoft/TypeScript/issues/53332
> [example] move GQLViewer into its own file

- ts/package.json
- ts/src/action/executor.test.ts
- ts/src/action/executor.ts
- ts/src/action/executor_long.test.ts
- ts/src/core/db.ts
- ts/src/testutils/action/complex_schemas.ts
- ts/src/testutils/db/temp_db.ts
ran into a situation where an action would just hang if we were creating lots of sub actions (which also had its own chain) in the observers below
the issue only applied if the sub-actions were in a `Promise.all`
If the sub-actions were in a good old serial loop, it would be fine
> release client in actions before running observers

- examples/ent-rsvp/backend/package-lock.json
- examples/ent-rsvp/backend/package.json
- examples/simple/package-lock.json
- examples/simple/package.json
- internal/cmd/cmd.go
- ts/package.json
- ts/src/scripts/custom_graphql.ts
- tsent/cmd/migrate_v0.1.go
- tsent/cmd/run_script.go
the ts-node infrastructure seems to be much slower and we don't need it
`node -r @swc-node/register -r tsconfig-paths` seems to do what I want when dealing with paths
followup to https://github.com/lolopinto/ent/pull/1417
> use node instead of ts-node with swc

- python/auto_schema/auto_schema/compare.py
- python/auto_schema/setup.py
simple check across versions shows COALESCE in postgres 14 and coalesce in 13.
follow-up to https://github.com/lolopinto/ent/pull/1442
> [auto_schema] case insensitive coaelsce check

- examples/simple/src/ent/generated/user/actions/create_user_action_base.ts
- internal/edge/edge.go
- internal/schema/schema.go
- internal/schema/schema_input_test.go
- ts/src/schema/schema.ts
follow-up to https://github.com/lolopinto/ent/pull/1452
it's annoying to have this change come in and codegen starts breaking and it seems very likely for there to be multiple ent schemas with multiple uuid indices to the same profile.
instead of doing it automatically, make the presence of `indexEdge` be the deciding factor for creating
e.g.
```ts
assignee_id: UUIDType({
index: true,
fieldEdge: {
schema: 'User',
// create edge `todos_assigned` in `User` so that we generate `queryTodosAssigned` and `todos_assigned` field in graphql
indexEdge: {
name: "todos_assigned",
},
},
})
```
> change generated index edge to be opt-in

- internal/field/field.go
- internal/tscode/base.tmpl
https://github.com/lolopinto/ent/issues/288 is wontfix so this code is dead. only automatically generating loaders for id fields. everything else is custom code with `Foo.loadCustom` or custom ent queries
> cleanup query from code in field

- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/schema/event_schema.ts
- examples/simple/src/schema/user_schema.ts
- examples/todo-sqlite/package-lock.json
- examples/todo-sqlite/package.json
- examples/todo-sqlite/src/graphql/generated/schema.gql
- examples/todo-sqlite/src/schema/account_schema.ts
- internal/schema/input/input.go
- internal/schema/node_data.go
- internal/schema/schema.go
- ts/package.json
- ts/src/parse_schema/parse.ts
- ts/src/schema/base_schema.ts
- ts/src/schema/schema.ts
use `showFoo` language instead of support to be more consistent with other ent things
follow-ups to https://github.com/lolopinto/ent/pull/1480, https://github.com/lolopinto/ent/pull/1472
> decouple canViewerSeeInfo and canViewerSeeEdit into different options

- ts/package.json
- ts/src/core/query/complex_custom_query.test.ts
- ts/src/core/query/query.ts
wrong construction led to sadness in generated query
apparently, didn't have a test for this case
follow-up to https://github.com/lolopinto/ent/pull/1493
> fix nulls first|last query when sort column is same as cursor col

- ts/src/graphql/index.ts
`@snowtop/ent/graphql` didn't have these imports
> update imports to expose gqlInterfaceType and gqlUnionType

- ts/src/action/orchestrator.ts
- ts/src/action/orchestrator_edge_data.test.ts
builds on top of https://github.com/lolopinto/ent/pull/1498, https://github.com/lolopinto/ent/pull/1499, https://github.com/lolopinto/ent/pull/1500
addresses part of https://github.com/lolopinto/ent/issues/1032
can also be used for regular edges but no need to since wrappers are generated in the builders
> New changeset apis that can be used to write global edges

- ts/src/core/base.ts
- ts/src/core/ent.ts
- ts/src/core/ent_custom_data.test.ts
- ts/src/core/loaders/query_loader.ts
- ts/src/core/query/custom_clause_query.ts
- ts/src/core/query_impl.ts
was initially going to add a `nullsPlacement` field but that was becoming ugly so finally changed `orderby` to something that's more flexible, supports multiple columns and easier to use
this should be ported back to loaders and ent queries
follow-up to https://github.com/lolopinto/ent/pull/1493
> change orderby in QueryDataOptions so that nullsPlacement can be configured for Foo.loadCustom queries

- .github/workflows/node.js.yml
- .gitignore
- ts/package-lock.json
- ts/package.json
- ts/src/action/orchestrator_upsert.test.ts
- ts/src/core/db.ts
- ts/src/core/ent.ts
- ts/src/core/ent_errors.test.ts
- ts/src/schema/postgres_schema_live.test.ts
- ts/src/testutils/db/temp_db.ts
update `better-sqlite3` to latest version
fixes https://github.com/lolopinto/ent/issues/1278
I believe sporadic error i was seeing was related to jest https://github.com/WiseLibs/better-sqlite3/issues/162
2 changes to make tests passe:
* instead of `instanceof Error` checks, also check the constructor's name is `SqliteError`
* instead of using `expect(promise).rejects`. do a try/catch 
also, adds WAL pragma as recommended in the README
> update better-sqlite3 

- ts/package-lock.json
- ts/package.json
- ts/src/schema/postgres_schema_live.test.ts
test had issues in github actions and had been skipped for longest time
fixes https://github.com/lolopinto/ent/issues/294
uses `pg-copy-streams` as indicated in description of issue
> fix long standing broken test

- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/graphql/generated/resolvers/comment_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/contact_email_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/contact_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/contact_phone_number_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/event_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/holiday_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/hours_of_operation_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/resolvers/user_list_deprecated_query_type.ts
- examples/simple/src/graphql/generated/schema.gql
- internal/cmd/cmd.go
- ts/package.json
- ts/src/scripts/custom_graphql.ts
when there's a mismatch between host environment and platform, we run into issues
there's ways around it but that seems annoying to recommend by default so changing the default and now swc can be opted into with `ENABLE_SWC`
changes `@swc-node/register` into an optional peer dependency 
follow-up to https://github.com/lolopinto/ent/pull/1417 and https://github.com/lolopinto/ent/pull/1422
addresses issue discussed in https://github.com/lolopinto/ent/issues/1496
tried a bunch of other things: [ts-node fork](https://github.com/lolopinto/ent/tree/ts-node-swc-patch), [assume yarn](https://github.com/lolopinto/ent/tree/yarn-changes), [moving installs around](https://github.com/lolopinto/ent/pull/1503  which didn't solve the issue
> change swc to not be enabled by default

- internal/build_info/build_info.go
- internal/codegen/codegen_processor.go
- internal/db/db_schema.go
if someone downgrades and then undoes the changes in the schema file but keeps schema.py and schema.sql, we'll give an error
this makes sure we don't do that
previous steps that led to error:
1. make a change e.g. event_schema.ts
2. run codegen
3. downgrade -- -1
4. comment out change in event_schema.ts
5. run codegen. this errors
this wouldn't have erorred
1. make a change e.g. event_schema.ts
2. run codegen
3. downgrade -- -1
4. git checkout src/schema
5. run codegen
difference is in step 4, we kept schema.py and schema.sql
follow-up to https://github.com/lolopinto/ent/issues/1441
> fix edge case after downgrade

- python/Pipfile
- python/Pipfile.lock
- python/auto_schema/auto_schema/compare.py
- python/auto_schema/auto_schema/env.py
- python/auto_schema/auto_schema/ops_impl.py
- python/auto_schema/auto_schema/runner.py
- python/auto_schema/auto_schema/script.py.mako
- python/auto_schema/tests/command_test.py
- python/auto_schema/tests/conftest.py
- python/auto_schema/tests/runner_test.py
- python/auto_schema/tests/testingutils.py
and make a bunch of changes to how things work because of that
* connection.execute() doesn't take string anymore. have to wrap in `sa.text()`
* `env.py`, wrap context configuration in `engine.connect()` 
* use `row._asdict()` to get rows whenever we query
* change tests to use new connections in `conftest.py` anytime we use `new_test_runner`
* change how we do full text indices logic since sqlalchemy added support for expression-based indices https://github.com/sqlalchemy/sqlalchemy/issues/7442
alembic still doesn't do it so still need to handle it https://github.com/sqlalchemy/alembic/issues/1098
Test Plan:
pytest
for example, delete the db and run upgrade and confirm it works
in examples/simple, `dropdb tsent_test`, `createdb tsent_test` and then `LOCAL_AUTO_SCHEMA=true tsent upgrade` …
> Update auto schema deps to latest 

- release_image/main.go
remove the alpha. it's been in production for almost a year. should be v1.0 based on semver but still have so many things to add, doesn't feel v1.0 yet
> new v0.1.0 docker release

- examples/simple/ent.yml
- examples/simple/src/graphql/generated/schema.ts
- examples/simple/src/graphql/resolvers/subscription_type.ts
- internal/codegen/config.go
- internal/graphql/generate_ts_code.go
- internal/graphql/ts_templates/schema.tmpl
subscriptions are complicated and there's a lot involved in it and how it should be implemented. so we just provide a way for the user to implement it themselves with `GraphQLObjectType` and we include in generated schema
addresses part of https://github.com/lolopinto/ent/issues/1544. doubt we'd do more than this in the foreseeable future
> ability to specify subscription type in graphql schema

- ts/package.json
- ts/src/action/action.test.ts
- ts/src/action/operations.ts
update edge time and data when there's a conflict
should this be configurable?
> update edge time when there's a conflict

- internal/graphql/generate_ts_code.go
i can't immediately recall why this is not also stored in processor.Schema.Enums
> pass global enums to custom graphql parsing to be resolved

- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/graphql/generated/mutations/bulk_upload_contact_type.ts
- examples/simple/src/graphql/generated/schema.gql
- examples/simple/src/graphql/mutations/import_contact.ts
- ts/package.json
- ts/src/graphql/graphql.test.ts
- ts/src/graphql/graphql.ts
accompaniment to https://github.com/lolopinto/ent/pull/1567/files
even after passing global enums to be resolved, we still need to allow it as valid argument
this also allows nodes as argument but the resulting schema will be invalid so that's fine
long-term, we can address this by changing data sent down if this becomes an issue
> allow enums to be args in custom queries and mutations

- internal/schema/input/input.go
was debugging something and saw that `CreateHolidayAction` in examples/simple seemed to always be modified
tracked it down to this field not being saved properly in `.ent/schema.json` because of the weird serialization being done with ActionField.MarshalJSON
fixes issue from https://github.com/lolopinto/ent/pull/1366
> fix optional in action only field not being serialized well

- examples/ent-rsvp/backend/src/ent/generated/address_base.ts
- examples/ent-rsvp/backend/src/ent/generated/auth_code_base.ts
- examples/ent-rsvp/backend/src/ent/generated/event_activity_base.ts
- examples/ent-rsvp/backend/src/ent/generated/event_base.ts
- examples/ent-rsvp/backend/src/ent/generated/guest_base.ts
- examples/ent-rsvp/backend/src/ent/generated/guest_data_base.ts
- examples/ent-rsvp/backend/src/ent/generated/guest_group_base.ts
- examples/ent-rsvp/backend/src/ent/generated/user_base.ts
- examples/simple/src/ent/generated/address_base.ts
- examples/simple/src/ent/generated/auth_code_base.ts
- examples/simple/src/ent/generated/comment_base.ts
- examples/simple/src/ent/generated/contact_base.ts
- examples/simple/src/ent/generated/contact_email_base.ts
- examples/simple/src/ent/generated/contact_phone_number_base.ts
- examples/simple/src/ent/generated/event_base.ts
- examples/simple/src/ent/generated/holiday_base.ts
- examples/simple/src/ent/generated/hours_of_operation_base.ts
- internal/tscode/base.tmpl
was looking at generated code and saw that we were awaiting and checking null here when we don't need to since the value is typed correctly
> [cleanup] don't await in a couple places where we don't need to

- examples/simple/ent.yml
- examples/simple/src/schema/schema.py
- internal/codegen/config.go
- internal/db/db_schema.go
- internal/db/db_schema.tmpl
- python/auto_schema/auto_schema/runner.py
- python/auto_schema/setup.py
- ts/src/core/config.ts
follow-up to https://github.com/lolopinto/ent/pull/1618
not all are relevant anymore e.g. referencing a deleted table or a function has been replaced by a newer one so you wanna use the latest version
3 states:
* all included default
* include list, only specified included
* exclude list, anything but specified included
> ability to indicate which custom_sql revisions are added to schema.sql

- python/Pipfile
- python/Pipfile.lock
- python/auto_schema/RELEASING.MD
- python/auto_schema/auto_schema/command.py
- python/auto_schema/auto_schema/script.py.mako
- python/auto_schema/setup.py
- python/auto_schema/tests/command_test.py
* create `__init__.py` for `auto_schema/util` added in https://github.com/lolopinto/ent/pull/1621
* use `ruff` for formatting to speed up squash_all when there's a huge file generated
* use a fork of `alembic` for now to get `ruff` support until `1.12.0` comes out
* add `#noqa` to `script.py.mako` so that custom revisions can still use `op.{method}` without having to add anything
* needed for tests to work without many changes to how tests work
> misc auto_schema changes

- python/auto_schema/auto_schema/runner.py
- python/auto_schema/pyproject.toml
- python/auto_schema/tests/conftest.py
- python/auto_schema/tests/runner_test.py
not sure how this happens but ran into this. this only saves an extra schema file since the next time things should be equal but it was confusing to me when i encountered this so fixing
> [auto_schema] handle slight changes in json when comparing server_default

- ts/src/action/operations.ts
- ts/src/action/transformed_orchestrator.test.ts
- ts/src/core/base.ts
- ts/src/core/clause.ts
- ts/src/core/context.ts
- ts/src/core/ent_custom_data.test.ts
- ts/src/core/ent_data.test.ts
- ts/src/core/loaders/assoc_count_loader.test.ts
- ts/src/core/loaders/assoc_edge_loader.test.ts
- ts/src/core/loaders/assoc_edge_loader.ts
- ts/src/core/loaders/object_loader.test.ts
- ts/src/core/loaders/query_loader.test.ts
- ts/src/core/loaders/raw_count_loader.test.ts
- ts/src/core/query_impl.ts
follow-up to https://github.com/lolopinto/ent/pull/1635
* use context in a few places that were missing e.g. `operations.ts`
* consolidate types in one place 
* add `join` to cache.QueryOptions and what it's checking
* use loader factory instead of loader in a bunch of tests so it's similar to production use cases 
* clear out as many manual cache clearing as possible. if the cache has to be manually cleared, it's a sign that something is broken and fixed it e.g. missing context or context not threaded through
* probably more
may be worth doing a breaking change to make Context required but cache can be optional to imrp
> misc context | cache fixes

- docs/docs/custom-graphql/gql-input-object-type.md
- docs/docs/custom-graphql/gql-interface-type.md
- docs/docs/custom-graphql/gql-object-type.md
- docs/docs/custom-graphql/gql-union-type.md
fixes https://github.com/lolopinto/ent/issues/1649
> remove reference to fixed bug

- docs/docs/custom-graphql/gql-input-object-type.md
- docs/docs/custom-graphql/gql-interface-type.md
- docs/docs/custom-graphql/gql-object-type.md
- docs/docs/custom-graphql/gql-union-type.md
This reverts commit e4c36aa29fcf2cdf92e08b7647294232531a5692.
reverts https://github.com/lolopinto/ent/pull/1651
https://github.com/lolopinto/ent/issues/1649 still open
> Revert "remove reference to fixed bug (#1651)"

- ts/package.json
- ts/src/core/base.ts
- ts/src/core/context.ts
so that the discardedLoaders doesn't keep growing unbounded
follow-up to https://github.com/lolopinto/ent/pull/1641
fixes issue where websockets can introduce really bad load because the list of discardedLoaders grows forever
> add reset() to reset Context Cache in websockets instead of just clearCache

- ts/src/core/clause.test.ts
- ts/src/core/clause.ts
done at Clause creation time instead of at query construction time
goes along with https://github.com/lolopinto/ent/pull/1637
used when we know the alias for the Clause which may be different from the alias for other parts of query. usually used in a join. used in other PR coming. all part of testing new APIs
> ability to override the alias of a Clause

- ts/src/core/base.ts
- ts/src/core/clause.test.ts
- ts/src/core/clause.ts
- ts/src/core/ent.ts
- ts/src/core/query/complex_custom_query.test.ts
- ts/src/core/query/custom_clause_query.ts
- ts/src/core/query/custom_query.ts
- ts/src/core/query/query.ts
- ts/src/core/query/shared_test.ts
- ts/src/core/query_impl.ts
- ts/src/graphql/query/shared_edge_connection.ts
- ts/src/testutils/builder.ts
- ts/src/testutils/db/temp_db.ts
builds on top of https://github.com/lolopinto/ent/pull/1672
depends on https://github.com/lolopinto/ent/pull/1672
addresses https://github.com/lolopinto/ent/issues/1660
`joinBETA` instead of `join` because I don't like the API and may end up changing it e.g. maybe it's own query class that has better ways of handling things instead of what we currently do with fieldsAlias and alias
> CustomClauseQuery support for joins

- ts/src/action/action.test.ts
- ts/src/action/operations.ts
- ts/src/action/orchestrator_upsert.test.ts
- ts/src/testutils/builder.ts
needed for test in https://github.com/lolopinto/ent/pull/1676 where the list of fields needs to change depending on the test and "returning *" returns extra fields we don't need in that case
we don't do select * when querying so this is consistent
> indicate list of fields to return in orchestrator instead of returning *

- docker_CHANGELOG.md
- release_image/main.go
- ts/Dockerfile
- ts/Dockerfile.tmpl
also changes the way node js images are built in the Dockerfile because old way was deprecated
> new release

- .github/workflows/e2e.yml
- .github/workflows/go_ci.yml
- docker_CHANGELOG.md
- docs/docs/advanced-topics/running-locally.md
- examples/simple/develop.Dockerfile
- examples/simple/docker-compose.dev.yml
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/ent/generated/contact_phone_number/actions/contact_phone_number_builder.ts
- examples/simple/src/ent/generated/hours_of_operation/actions/hours_of_operation_builder.ts
- internal/graphql/generate_ts_code.go
- release_image/main.go
- ts/Dockerfile
- ts/Dockerfile.tmpl
- ts/package-lock.json
- ts/package.json
fixes https://github.com/lolopinto/ent/issues/1715
> update swc and ts-node to latest versions

- docker_CHANGELOG.md
- examples/simple/src/ent/generated/contact_phone_number/actions/contact_phone_number_builder.ts
- examples/simple/src/ent/generated/event/actions/edit_event_rsvp_status_action_base.ts
- examples/simple/src/ent/generated/hours_of_operation/actions/hours_of_operation_builder.ts
- examples/todo-sqlite/src/ent/generated/account/actions/account_builder.ts
- examples/todo-sqlite/src/ent/generated/account/actions/create_account_action_base.ts
- examples/todo-sqlite/src/ent/generated/account/actions/edit_account_action_base.ts
- examples/todo-sqlite/src/ent/generated/account/actions/edit_account_todo_status_action_base.ts
- examples/todo-sqlite/src/ent/generated/tag/actions/tag_builder.ts
- examples/todo-sqlite/src/ent/generated/todo/actions/create_todo_action_base.ts
- examples/todo-sqlite/src/ent/generated/todo/actions/todo_builder.ts
- examples/todo-sqlite/src/ent/generated/workspace/actions/create_workspace_action_base.ts
- examples/todo-sqlite/src/ent/generated/workspace/actions/edit_workspace_action_base.ts
- examples/todo-sqlite/src/ent/generated/workspace/actions/workspace_builder.ts
- examples/todo-sqlite/src/schema/patterns/base.ts
- internal/action/action.go
- internal/action/interface.go
- internal/field/field.go
broken in https://github.com/lolopinto/ent/pull/1711 by always returning field.SingleFieldPrimaryKey() as required field
now we force optional if a default value on create and has default value on create so that has precedence
> fix id fields with disable user graphql editable

- internal/field/field.go
led to disableBuilderType in UUIDType not being respected when defaultValueOnCreate is true and disableUserGraphQLEditable is true
> fix disableBuilderType missing in field.Clone()

- ts/src/core/base.ts
- ts/src/core/query_impl.ts
When running a query with a join, to order by a field not on the main table, we have to disable the alias prefixing of columns in the order by clause.
> Add ability to remove alias from order by clause

- ts/src/action/operations.ts
- ts/src/core/base.ts
- ts/src/core/context.ts
- ts/src/core/ent.ts
- ts/src/core/loaders/query_loader.ts
- ts/src/core/query/custom_clause_query.ts
- ts/src/core/query_impl.ts
When using joins in `CustomClauseQuery`, if you want to sort by a column on a joined table, you need to include that column in the select fields. However, if you are using aliases, there's no way to add a column not on the main table alias. This adds a new field type beyond just `string` that lets you specify the alias for just that single field, which will override the default alias for the table.
This addresses #1752
> Add an ability to specify field aliases on a per-field basis

- internal/tscode/builder.tmpl
The only thing I'm not 100% sure about is soft deletes, but I believe those get their delete actions converted to update actions, so it won't have any effect here.
Fixes #1819
> Ensure delete actions remove inbound edges

- internal/graphql/generate_ts_code.go
`float` is not a valid TS type. It needs to be `number`.
Per the comment on line 65 above, in the `graphql.ts` file `knownAllowedNames` is already correctly defined as such:
```ts
export const knownAllowedNames: Map<string, string> = new Map([
["Date", "Date"],
["Boolean", "boolean"],
["Number", "number"],
["String", "string"],
// TODO not right to have this and Number
["Int", "number"],
["Float", "number"],
["ID", "ID"],
["JSON", "any"],
["Node", "Ent"],
]);
```
Fixes #1826
> Fix invalid generated TS "float" type

- ts/src/graphql/query/edge_connection.ts
The edge connection work I previously did to enable async custom connections highlighted an existing bug and also introduced a new one.
The existing bug: `args.cursor` should have been `args.before`.
The new bug: `args.last` was and should be `args.after`.
> Fix edge connection pagination

- ts/src/core/clause.test.ts
- ts/src/core/clause.ts
- ts/src/core/db.ts
- ts/src/core/ent.ts
- ts/src/core/loaders/assoc_edge_loader.ts
- ts/src/core/query/assoc_query.test.ts
- ts/src/core/query/assoc_query.ts
- ts/src/core/query/assoc_query_global.test.ts
- ts/src/core/query/assoc_query_sqlite.test.ts
- ts/src/core/query/assoc_query_sqlite_global.test.ts
- ts/src/core/query/complex_custom_query.test.ts
- ts/src/core/query/custom_clause_query.ts
- ts/src/core/query/custom_query.ts
- ts/src/core/query/custom_query_live.test.ts
- ts/src/core/query/custom_query_sqlite.test.ts
- ts/src/core/query/custom_query_sqlite_global.test.ts
- ts/src/core/query/query.ts
- ts/src/core/query/shared_test.ts
- ts/src/core/query/unique_col_query.test.ts
- ts/src/core/query_impl.ts
- ts/src/graphql/query/shared_edge_connection.ts
- ts/src/testutils/db_mock.ts
- ts/src/testutils/ent-graphql-tests/index.ts
- ts/src/testutils/fake_data/user_query.ts
When using `BaseEdgeQuery`, if you are sorting over multiple non-unique columns, the pagination was coming back incorrectly because the cursor was only storing a single sort column (plus the cursor key, usually the primary key uuid). This changes queries to allow for any number of sort columns and to run through the same SQL-generation despite the amount or type of sorting going on.
Fixes #1750 and #1751
> Adjust edge queries to support multiple sort columns

- ts/src/core/query/custom_clause_query.ts
- ts/src/graphql/query/custom_clause_edge_connection.test.ts
- ts/src/graphql/query/edge_connection.ts
- ts/src/graphql/query/shared_edge_connection.ts
to address https://github.com/lolopinto/ent/issues/1836
> RFC: fix CustomClauseQuery for #1836

- ts/src/core/base.ts
- ts/src/core/db_clause.test.ts
- ts/src/core/query_impl.ts
- ts/src/testutils/db_mock.ts
Pretty simple, just lets you specify a type of join if you want to. Fixes #1839.
> Join types

- examples/ent-rsvp/backend/src/ent/generated/address/actions/create_address_action_base.ts
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/src/ent/tests/contact.test.ts
- examples/simple/src/graphql/generated/mutations/input/attachment_input_type.ts
- examples/simple/src/graphql/generated/resolvers/contact_info_type.ts
- examples/simple/src/graphql/generated/resolvers/feedback_type.ts
- examples/simple/src/graphql/generated/resolvers/with_day_of_week_type.ts
- examples/simple/src/graphql/generated/schema.gql
- examples/simple/src/graphql/tests/contact_type.test.ts
- internal/graphql/generate_ts_code.go
- ts/package.json
- ts/src/schema/schema.ts
- ts/src/schema/struct_field.test.ts
- ts/src/schema/struct_field.ts
fixes https://github.com/lolopinto/ent/issues/1850
derived fields in structs were being dropped
and small update as follow-up to https://github.com/lolopinto/ent/pull/1851
> save polymorphic types in structs

- internal/cmd/cmd.go
- internal/graphql/generate_ts_code.go
- internal/schema/input/parse_ts.go
pulled from https://github.com/lolopinto/ent/pull/1858/files
was missing in parse_schema path
> port .swcrc logic into central location and reuse
